### PR TITLE
[examples] Update Vercel Next.js example template to 12.0.1

### PR DESCRIPTION
**Pull request by dbredvick**
### Related Issues
Our example Next.js application was previously pinned to version `11.1.2`, this updates it to `12.0.1`.

#### Tests

- [ ] The code changed/added as part of this PR has been covered with tests
- [x] All tests pass locally with `yarn test-unit`

#### Code Review

- [x] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

### CODE REVIEW

**Review by leerob — APPROVED** [review]
Or maybe we just put latest?

**Review by styfle — APPROVED** [review]
Let's also deploy it to https://nextjs.examples.vercel.com/

**Comment by dbredvick** [comment]
> Or maybe we just put latest?

@leerob I like the idea of this always matching the output of `create-next-app`. We pin to a specific version there, but I could see `@latest` making more sense?

**Comment by styfle** [comment]
Lets match `create-next-app`

**Pull request merged**
