### PR TITLE
[examples] Add Apollo-Server example

### PR DESCRIPTION
**Pull request by ilya-buligin**
This is an example of a simple GraphqQL server built on Serverless Functions with Apollo-Server.

### CODE REVIEW

**Comment by elderapo** [comment]
I couldn't figure out why my frontend app (hosted on `now`) wasn't working after switching from `apollo-server` to `apollo-server-micro`. Correctly handling cors was an answer:

```ts
const handler = apolloServer.createHandler({ path: "/api/graphql" }); 
 
export default async (req: NowRequest, res: NowResponse) => { 
  res.setHeader("Access-Control-Allow-Origin", "*"); 
  res.setHeader("Access-Control-Allow-Methods", "GET,POST"); 
  res.setHeader( 
    "Access-Control-Allow-Headers", 
    "Content-Type, Authorization, Content-Length, X-Requested-With" 
  ); 
 
  if (req.method === "OPTIONS") { 
    return res.send(200); 
  } 
 
  return handler(req, res); 
}; 
```

**Comment by ilya-buligin** [comment]
> I couldn't figure out why my frontend app (hosted on `now`) wasn't working after switching from `apollo-server` to `apollo-server-micro`. Correctly handling cors was an answer:
> 
> ```ts
> const handler = apolloServer.createHandler({ path: "/api/graphql" }); 
>  
> export default async (req: NowRequest, res: NowResponse) => { 
>   res.setHeader("Access-Control-Allow-Origin", "*"); 
>   res.setHeader("Access-Control-Allow-Methods", "GET,POST"); 
>   res.setHeader( 
>     "Access-Control-Allow-Headers", 
>     "Content-Type, Authorization, Content-Length, X-Requested-With" 
>   ); 
>  
>   if (req.method === "OPTIONS") { 
>     return res.send(200); 
>   } 
>  
>   return handler(req, res); 
> }; 
> ```

You should disable body parsing in config:
```
export const config = {
  api: {
    bodyParser: false,
  },
};
```

**Comment by elderapo** [comment]
@AgentX001, it doesn't solve the issue. The issue is browsers send a request with `OPTIONS` to check if server supports cors or not. `apollo-server-micro` only accepts `GET` & `POST` request methods. For any other method (including `OPTIONS`) it returns `405` which causes (copied from chrome devtools):
```
OPTIONS http://localhost:3000/api/graphql 405 (Method Not Allowed)
Access to fetch at 'http://localhost:3000/api/graphql' from origin 'http://localhost:35810' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

I am not sure but maybe this should be reported at https://github.com/apollographql/apollo-server?

**Comment by ilya-buligin** [comment]
> @AgentX001, it doesn't solve the issue. The issue is browsers send a request with `OPTIONS` to check if server supports cors or not. `apollo-server-micro` only accepts `GET` & `POST` request methods. For any other method (including `OPTIONS`) it returns `405` which causes (copied from chrome devtools):
> 
> ```
> OPTIONS http://localhost:3000/api/graphql 405 (Method Not Allowed)
> Access to fetch at 'http://localhost:3000/api/graphql' from origin 'http://localhost:35810' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
> ```
> 
> I am not sure but maybe this should be reported at https://github.com/apollographql/apollo-server?

@elderapo thanks for your note. I added CORS support to example. Does it solve your problem?

**Comment by timothyis** [comment]
Hi @AgentX001. Thank you very much for taking the time to submit this contribution.

Currently, we have decided to focus all of our efforts on the frontend experience and the Jamstack methodology. This means that we encourage our users to deploy a frontend framework and use external services for backend behavior.

In this case, I recommend that developers use a service such as [Hasura](hasura.io) to manage GraphQL and use that with their front-end apps on Vercel.

Thanks again!

**Pull request closed without merging**
