### PR TITLE
[now dev] Fix "zero-config" detection

### PR DESCRIPTION
**Pull request by TooTallNate**
Only apply the zero-config processing logic if one of these is true:

  1. No `now.json`
  2. No `builds` array in `now.json`
  3. `builds` array is empty in `now.json`

### CODE REVIEW

**Comment by styfle** [comment]
@TooTallNate You specifically wrote  `now dev` so does that mean the logic to detect zero config is different for `now` vs `now dev`?

**Comment by AndyBitz** [comment]
@styfle It has to be different due to hot reloading. Files can change anytime and then the config needs to get updated.

**Comment by styfle** [comment]
@AndyBitz I understand that hot reloading doesn't need to be shared.

I just mean we could have one `export function isZeroConfig(json)` that is used for both `now` and `now dev`. Then hot reloading can be used to check it again when the file is modified.

**Comment by AndyBitz** [comment]
@styfle I see, though, looking at the code again it does exactly what `now` is doing. When there are no `builds` zero-config is applied.

**Review by styfle — APPROVED** [review]

**Comment by styfle** [comment]
I saw that api-deployments has the production logic which is similar to what you implemented here. I would like to start brainstorming ways we can avoid duplicating these types of features so that it can live in one place and work the same for both `now` and `now dev`.

**Comment by TooTallNate** [comment]
Lets go with #2561 instead.

**Pull request closed without merging**
