### PR TITLE
[now-build-utils] Remove `NOW_BUILDER_ANNOTATE`

### LINKED ISSUE #2843: Introduce debug() helper for Builders
As you can see here:

image

And here:

image

We're logging way too much. Those things should all be logged by a `debug` function instead. Depending on where the Builder is then run, the behavior of this function will change:

- In `now dev`, it just hides the log line until `--debug` is defined.
- In production, it annotates the log line with something that lets front filter it out, except if the DEBUG checkbox is checked in the UI.

### PR DESCRIPTION
**Pull request by thasophearak**
This PR fix: https://github.com/zeit/now/issues/2843#issuecomment-531503513

### CODE REVIEW

**Review by styfle — APPROVED** [review]
So no more prefix? How will `front` be able to toggle the logs on/off? Or does front not use this debug method here?

**Review by leo — APPROVED** [review]

**Comment by leo** [comment]
@styfle We've decided to have the user set `--debug` when deploying instead, to avoid unnecessarily logging lines that the user will never get to see. It just makes everything slower, more costly and the log render logic on the clients more complicated.

**Review by TooTallNate — APPROVED** [review]

**Review by AndyBitz — APPROVED** [review]

**Comment by styfle** [comment]
@sophearak Do we need to coordinate this PR with front?

**Comment by thasophearak** [comment]
@styfle I think, it is okay to do it explicitly. Since it's just more or less remove annotate filter.

I believed, logs continue to work just fine with both front and Now CLI.

**Pull request merged**
