### PR TITLE
Added support for HTTP/2

### PR DESCRIPTION
**Pull request by pranaygp**
This does 2 things:
1. Swaps out the `http1` agent for a shinier and faster `http2` agent (using https://github.com/grantila/fetch-h2)
2. Changes the files upload concurrency implementation to use a semaphore instead of naive batching

http2 has a huge benefit in that it lets you make multiple requests over the same connection instead of having to create a new connection for each http request. This gives us **massive** gains for the file upload process.

I'll post stats to compare the old http1(.1) implementation vs the new http2 implementation tomorrow :)

Since this change affects more than just file uploads (swapping out the agent itself), we should run more tests on other products. I'm not sure of a good way to setup tests for some things (domains, for example) just to make sure nothing breaks.

### CODE REVIEW

**Comment by rauchg** [comment]
Note: this means we have to `pkg` with the `--expose-http2` flag and latest Node 8.x

**Comment by leo** [comment]
I'm voting for waiting for HTTP/2 to get stable in Node.js and then use it without a flag (since we can't foresee what might happen with the experimental one).

**Comment by pranaygp** [comment]
@leo Since we know and can test all the different **types** of requests made over http2, it might not be a big deal. Also, if I understand correctly, http2 in node is marked experimental because there may be api breaking changes in a future version. By using pkg, that's something we don't have to worry about

**Comment by rauchg** [comment]
@leo @pranaygp something that could work well is to only enable http2 in canary

**Comment by leo** [comment]
Sure. Every PR goes to `canary` first either way. Let me know!

**Comment by rauchg** [comment]
@leo but it could be one of those situations where we can _only_ use HTTP2 in canary until we're comfortable. @pranaygp would adding such a flag be possible?

**Comment by pranaygp** [comment]
Hopefully, this suffices @rauchg ?

https://github.com/zeit/now-cli/pull/953/files#diff-3a55845f63e7f7f9d9237b79de0d0ca1R13

**Comment by leo** [comment]
@pranaygp That's perfect! I mean, either way we would only keep this commit on the canary channel, so it will be the only one using HTTP/2. But now that you've added the version check, you even covered the case of us accidentally pushing this commit to the stable channel.

**Comment by leo** [comment]
All in all, this looks ready to merge on the canary channel to me. Would you mind posting some stats on the difference to HTTP/1, @pranaygp?

**Review by leo — APPROVED** [review]

**Comment by pranaygp** [comment]
Here are my benchmark tests:

**HTTP/batching(n)**: Time taken to upload n files in batches of 10 files at a time over HTTP1(.1). We wait for a batch to complete before starting the next batch
**HTTP(n)**: Time taken to upload n files in over HTTP1(.1) with atmost 50 files conccurently. If a file ever completes uploading,we start another file. At any point in time, we have 50 max parallel requests.
**HTTP2(n)**: Time taken to upload n files in over HTTP/2 with atmost 50 files conccurently. If a file ever completes uploading,we start another file. At any point in time, we have 50 max parallel requests.

```
100 files test (each file is ~2KB)
HTTP/batching(100):  14771.037ms
HTTP(100):            9819.834ms
HTTP2(100):           3067.199ms
```

```
500 files test (each file is ~2KB)
HTTP/batching(500):  62360.622ms
HTTP(500):           48156.546ms
HTTP2(500):           7807.020ms
```

```
1000 files test (each file is ~2KB)
HTTP/batching(1000): 139226.707ms
HTTP(1000):           84481.409ms
HTTP2(1000):          14382.655ms
```

Each test file was generated by concatenating ~200 random words from the english dictionary with spaces to separate them.

It's easy to see the massive improvements with `http2`. With both the optimizations that this PR brings, the upload process is **~80-90%** faster

**Comment by pranaygp** [comment]
FTR, I did a test with using multiple sockets in a socket pool and balancing between them using round robin. I also split the max concurrent requests between the different sockets.
That doesn't seem to make things faster. In fact, pretty often, it turns out to be slower to do that.

The variance of these benchmarks is pretty high, so don't trust them, but I never once noticed a test with >1 socket to be faster than a single socket:

```
1 socket  (80 concurrent): 4733.859ms
2 sockets (80 concurrent): 4850.555ms
3 sockets (80 concurrent): 5142.619ms
4 sockets (80 concurrent): 6075.720ms
```

**Pull request merged**
