### PR TITLE
[cli] Change `vc env pull` default output file to `.env.local`

### PR DESCRIPTION
**Pull request by dan-stowell**
`vc deploy` ignores `.env.local`. To make sure we don't inadvertently push people's secrets to source control, have all environment pulls default to writing to `.env.local`.

[Linear ticket](https://linear.app/vercel/issue/VCCLI-461/change-pull-from-env-to-envlocal-by-default)

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
~~Does `vc dev` need to be updated to read `.env.local`?~~

Looks like we decided that `vc dev` should be changed to stop reading `.env` entirely.

**Review by styfle — COMMENTED** [review]
Don't forget to update `--help` as well as vercel.com/docs

**Comment by dan-stowell** [comment]
@styfle does `MAJOR` mean we need to bump the major version for this change?

**Comment by styfle** [comment]
@dan-stowell Yes this is semver-major because its a breaking change (needs the label too)

**Review by cb1kenobi — DISMISSED** [review]
Tested and works as advertised.

**Review by EndangeredMassa — DISMISSED** [review]
Should we update these references to `.env` as well?

- errors/missing-env-file.md - should refer to `.env.local`?
- examples/sanity/.env.template - should be `.env.local.template`?
- packages/cli/src/util/dev/server.ts - line 674 and 675 should use `.env.local` and maybe fall back to `.env`?
- packages/cli/src/util/dev/types.ts - comments in `EnvConfigs` should refer to `.env.local`

I'm not positive how best to update `dev/server.ts`, but I think we should take a stab at them in this PR.

**Comment by dan-stowell** [comment]
> Should we update these references to `.env` as well?
> 
> * errors/missing-env-file.md - should refer to `.env.local`?

Done & pushed.

> * examples/sanity/.env.template - should be `.env.local.template`?

Done & pushed.

> * packages/cli/src/util/dev/server.ts - line 674 and 675 should use `.env.local` and maybe fall back to `.env`?
> * packages/cli/src/util/dev/types.ts - comments in `EnvConfigs` should refer to `.env.local`

Based on discussion in [Linear](https://linear.app/vercel/issue/VCCLI-65/update-vc-dev-to-use-vercelenvdevelopmentlocal), it seems that we do not want `vc dev` to read from `.env` at all. If that's the case, I'd like to make that change in a separate pull request.

**Review by styfle — DISMISSED** [review]

**Review by EndangeredMassa — DISMISSED** [review]

**Review by cb1kenobi — DISMISSED** [review]
LGTM

**Review by styfle — APPROVED** [review]

**Review by cb1kenobi — APPROVED** [review]

**Pull request merged**
