### PR TITLE
🐛 Handle --token deployments

### PR DESCRIPTION
**Pull request by albinekb**
https://zeit-community.slack.com/archives/C1TMPLCKS/p1493739798947303
image

### CODE REVIEW

**Comment by TooTallNate** [comment]
Was adding the `yarn.lock` file intentional?

**Comment by albinekb** [comment]
Oh no, sorry @tootallnate, should I add it to the gitignore if you don't want yarn.lock?

**Comment by leo** [comment]
Yep! 😊

**Comment by albinekb** [comment]
Fixed @leo @TooTallNate 👍

**Comment by matheuss** [comment]
Will review later 🕵️

**Comment by dariye** [comment]
@matheuss is this still being reviewed or is the team working on another solution to work with tokens deployments for `now@^5.1.0`

**Comment by matheuss** [comment]
Closed in favor of 8b306e657b30e5983eb08c1caa03eb8ec19fc65d 🙌 Thank you @albinekb

**Pull request closed without merging**
