### PR TITLE
[cli] Add `expect` dev dependency to fix type error in `toOutput`

### PR DESCRIPTION
**Pull request by TooTallNate**
Also make the timeout print what was buffered to help with debugging failed tests.

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Bummer its 5MB just for a type https://packagephobia.com/result?p=expect@29.5.0

**Comment by cb1kenobi** [comment]
Where is the type error being displayed? When tests are being run?

**Comment by TooTallNate** [comment]
@styfle It's not a new dependency though (it's a transient dependency of `jest`). In fact, if you look at the lockfile, this actually _removes_ an older version of `expect` and a few others. The red squiggly was probably a side-effect of switching over to pnpm.

**Comment by TooTallNate** [comment]
@cb1kenobi You normally wouldn't see it, since we don't validate TS errors for test files. But it's a red squiggly in the `toOutput.ts` file.

**Comment by cb1kenobi** [comment]
@TooTallNate I see it now! It's right there!

**Review by cb1kenobi — APPROVED** [review]

**Comment by EndangeredMassa** [comment]
This version doesn't affect the build container.

**Pull request merged**
