### PR TITLE
[tests] add "no only" and "no skip" eslint rules

### PR DESCRIPTION
**Pull request by lucleray**
Add [eslint-plugin-jest](https://github.com/jest-community/eslint-plugin-jest) and enable two rules to lint with errors when using `.skip` or `.only` in tests.

### CODE REVIEW

**Review by TooTallNate — APPROVED** [review]
Awesome!

**Review by styfle — APPROVED** [review]
Amazing! 😍 

Does this also work for ava? Since the cli tests use ava but every other package uses jest.

**Comment by styfle** [comment]
Seems like this didn't work 🤔 

```
Run yarn run lint
$ eslint . --ext .ts,.js

/home/runner/work/now/now/packages/now-cli/test/integration-v1.js
##[error]  40:9  error  Test is missing function argument  jest/no-disabled-tests
```

**Comment by lucleray** [comment]
@styfle I've ignored this error since it's not relevant. I've checked and it works on ava tests too. Alternatively, we can try [eslint-plugin-no-only-tests](https://www.npmjs.com/package/eslint-plugin-no-only-tests) but it doesn't lint `test.skip`.

**Review by styfle — APPROVED** [review]
:shipit:

**Pull request merged**
