### PR TITLE
[remix] add edge runtime support

### LINKED ISSUE #8788: Inconsistency between edge functions and edge runtime
When I serve [this file](https://github.com/theMosaad/remix-vercel-edge/blob/main/.vercel/output/functions/render.func/api/index.js) locally via edge-runtime, it works fine. However, when I deploy the same file to Vercel's edge functions, I get the below error:
```
TypeError: Parsing a Body as FormData requires a Content-Type header
```
I identified that awaiting `request.formData()` on [this line](https://github.com/theMosaad/remix-vercel-edge/blob/main/app/routes/index.tsx#L10) is what causes this error.

## To reproduce

1. Visit https://remix-vercel-edge-mosaad.vercel.app/ or use this repo to deploy your own https://github.com/theMosaad/remix-vercel-edge 
2. Click "submit"

Expectation: See the name logged in the functions logs like it gets logged in the terminal when running this example locally
Reality: `TypeError: Parsing a Body as FormData requires a Content-Type header.`

### PR DESCRIPTION
**Pull request by theMosaad**
### Feature
Support deploying Remix to Vercel's edge functions.

### Demo
This example is built locally with this patch: https://github.com/theMosaad/remix-vercel-edge

This also fixes https://github.com/vercel/vercel/issues/8788

P.S. Please advise if there's a more accurate way of emulating Vercel's production edge runtime locally.

### CODE REVIEW

**Comment by leerob** [comment]
On submit for the action, I'm seeing this.
CleanShot 2022-11-22 at 21 44 14@2x

**Comment by theMosaad** [comment]
> On submit for the action, I'm seeing this. CleanShot 2022-11-22 at 21 44 14@2x

I believe you're using the deployed version https://remix-vercel-edge-mosaad.vercel.app? In such case, this error is expected.

It's related to Vercel's implementation of the edge-runtime which i cannot patch and deploy as it falls outside of the Build Output API:
https://github.com/vercel/vercel/blob/dba337f1484311f061cc0551ba59a59aff3180d0/packages/node/src/edge-functions/edge-handler-template.js#L16-L31

However, I was able to patch it locally by installing [Vercel's edge-runtime](https://edge-runtime.vercel.app/getting-started) then modifying the edge function implementation https://github.com/theMosaad/remix-vercel-edge/blob/1ca0968da87ed9c2b242b743e055822f46b6a041/server-dev.js#L37-L55

Now, when I submit the action locally, the submitted values is logged in the terminal without an error in the frontend
value from action submit is logged in the terminal

P.S. I'm aware that my patch is hacky as I'm not sure about the purpose of the original piece of code. Once someone can point that out, I can work on a better solution that fixes this issue while not affecting the original purpose of that piece of code.

**Comment by leerob** [comment]
Going to close this in favor of https://github.com/vercel/vercel/pull/9375 – thank you so much for pushing this forward! I've also sent you the details on how to test the other PR. We greatly appreciate it 🙏

**Comment by theMosaad** [comment]
> Going to close this in favor of #9375 – thank you so much for pushing this forward! I've also sent you the details on how to test the other PR. We greatly appreciate it 🙏

Right back at you with the appreciation! I tested it and it solves https://github.com/vercel/vercel/issues/8788. Demo: https://remix-vercel-edge-beta.vercel.app/

I also used tested it on a [larger applications with many routes](https://notionicons-qzy67yoby-notion-icons.vercel.app/) and everything works well! 
Note: Auth doesn't properly work as I need to move encryption functions from Node to Web API but those have nothing to do with https://github.com/vercel/vercel/pull/9375.

**Comment by TooTallNate** [comment]
@theMosaad And a big <picture data-single-emoji=":thank_you:" title=":thank_you:">:thank_you:</picture> to you as well, because your PR here was the starting point for our reimagined version 🙇

**Pull request closed without merging**
