### PR TITLE
XO Happiness

### PR DESCRIPTION
**Pull request by lukeed**
Partially satisfies #92 

**Done:**

- `ava/no-ignored-test-files`
- `no-case-declarations`
- `no-useless-escape`

**Notes re:Remaining**
- `import/no-unresolved`

  Takes issue with `../../package` imports. If changed to `../../package.json`, new errors thrown about an unexpected json extension (`import/extensions`).

- `max-depth`
- `complexity`

  These two, if to be fixed, go hand-in-hand. A handful of functions (mostly `bin/*`) are too deep / have too many blocks according to XO; slicing them will require some refactoring. I'm waiting for a sign-off on this specifically before continuing.

- `no-use-before-define`

  Like the previous two, most of `lib/get-files.js` will have to be shifted around. And, unfortunately in [some cases](https://github.com/zeit/now-cli/blob/master/lib/get-files.js#L226-L237), it may not be able to satisfy this rule without some sub-optimal checks.

- `unicorn/no-process-exit`
  
  Easy one. [This](https://github.com/zeit/now-cli/blob/master/lib/utils/check-path.js#L50) is the only error. Not sure if `throw Error()` would suffice.

- `no-control-regex`
  
  TBH, no idea what this is. XO does not like `\x1b` from [here](https://github.com/zeit/now-cli/blob/master/lib/strlen.js#L2) & there appears to be no workaround...(because it's a hidden character?)

### CODE REVIEW

**Comment by leo** [comment]
WOW! Thanks a lot! 😊 🔥

**Comment by lukeed** [comment]
No problem @leo 😃 Unfortunately two of the remaining will never be happy; possibly three. Do you happen to know if `throw`ing in this case will achieve the desired behavior?

**Comment by leo** [comment]
Sure! I don't see a reason why we shouldn't throw instead. You're probably talking about replacing `process.exit()`, or what?

**Comment by lukeed** [comment]
Correct. Replacing `process.exit()` with a `throw` is all that's needed to appease XO. I'm only asking because I haven't checked out now's error handling.

**Pull request merged**
