### PR TITLE
[next] Fix edge runtime for route groups

### LINKED ISSUE #43458: [NEXT-947] The experimental-runtime fails with ReferenceError: self is not defined when used inside a route group
### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```
Operating System:
  Platform: darwin
  Arch: x64
  Version: Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64
Binaries:
  Node: 16.18.0
  npm: 8.19.2
  Yarn: 1.22.19
  pnpm: 7.13.5
Relevant packages:
  next: 13.0.5
  eslint-config-next: 13.0.5
  react: 18.2.0
  react-dom: 18.2.0
```

### What browser are you using? (if relevant)

_No response_

### How are you deploying your application? (if relevant)

Vercel

### Describe the Bug

Using the `experimental-edge` runtime fails with the following error when used inside a route group.

```
ReferenceError: self is not defined
    at Object.<anonymous> (/var/task/.next/server/app/(marketing)/stats/page.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.requirePage (/var/task/node_modules/.pnpm/next@13.0.6-canary.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/require.js:88:12)
    at /var/task/node_modules/.pnpm/next@13.0.6-canary.1_biqbaboplfbrettd7655fr4n2y/node_modules/next/dist/server/load-components.js:37:73
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  page: '/stats'
}
RequestId: Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

Given the following file structure:

```
app
├── page.tsx ✅
├── nested
│   └── page.tsx ✅
├── (group)
│   └── group
│       └── page.tsx ❌
└── (another-group)
    └── another-group
        └── page.tsx ❌  
```

With `export const runtime = "experimental-edge"`, the following is observed:

- `/` - Works
- `/nested` - Works
- `/group` - Fails
- `/another-group` - Fails

I checked if having a `layout.tsx` has any effect on grouping. It does not.

### Expected Behavior

Expects the `experimental-edge` runtime to work inside route groups.

### Link to reproduction - Issues with a link to complete (but minimal) reproduction code will be addressed faster

https://github.com/shadcn/next-debug-edge-runtime

### To Reproduce

See the links below:

1. ✅ `experimental-edge` runtime works for **root page**: https://next-debug-edge-runtime.vercel.app
2. ✅ `experimental-edge` runtime works for a **nested page**: https://next-debug-edge-runtime.vercel.app/nested-with-layout
3. ❌ `experimental-edge` runtime does not work for a **grouped page with layout**: https://next-debug-edge-runtime.vercel.app/group-no-layout
4. ❌ `experimental-edge` runtime does not work for a **grouped page without layout**: https://next-debug-edge-runtime.vercel.app/group-with-layout

<sub>[NEXT-947](https://linear.app/vercel/issue/NEXT-947/the-experimental-runtime-fails-with-referenceerror-self-is-not-defined)</sub>

### PR DESCRIPTION
**Pull request by ijjk**
This ensures we use the correct short name when generating edge functions with route groups from app directory. 

Example deployment with fix can be seen here https://next-debug-edge-runtime-1ar7agbjh-vtest314-ijjk-testing.vercel.app/group-no-layout

Fixes: https://github.com/vercel/next.js/issues/43458

### CODE REVIEW

**Review by shuding — DISMISSED** [review]

**Review by t3dotgg — DISMISSED** [review]
Working great for me in prod!

**Review by huozhi — DISMISSED** [review]

**Comment by djfarrelly** [comment]
Hi @ijjk - how can I use this in production? We've encountered this issue and with Next 13.2.x w/ app dir it won't work for me. Do I need to set the `@vercel/next` builder in the `vercel.json` file to get this to work correctly? 

I would love to know what we can do to opt in b/c we're seeing slowness and I'd like to move our app dir project 100% to edge functions.

**Comment by ijjk** [comment]
@djfarrelly this should now be available in production, please re-deploy your project and give it a try!

**Comment by djfarrelly** [comment]
Thanks @ijjk! My latest deploy worked correctly now - I appreciate the help!

**Pull request merged**
