### PR TITLE
Add suport for now.js config file

### PR DESCRIPTION
**Pull request by rigwild**
Following this conversation : [https://spectrum.chat/zeit/now/configuration-with-a-now-js-file~85c8cf20-858c-4c23-b477-3979b719553e](https://spectrum.chat/zeit/now/configuration-with-a-now-js-file~85c8cf20-858c-4c23-b477-3979b719553e)

User @Ignigena suggested to add support for now.js config files. The goal is to have dynamic config files.

Example : 
```js
// now.js
modules.exports = {
  version: 2,
  builds: [
    { src: '*.ts', use: '@now/node@canary' }
  ]
}
```

I think this could be useful.
After I made this I noticed that the variable name I used `readConfigFile` was also used in other files like `src/index.js`, so I don't know if that's a problem.

### CODE REVIEW

**Comment by rigwild** [comment]
I'm adding a complete example to show how it could be useful.

Here is my file structure :
```md
+-- now.js
+-- public
|   +-- header.html
+-- src
|   +-- dir1
|   |   +-- index.ts
|   +-- dir2
|   |   +-- index.ts
```
Here is the content of `now.js` :
```js
const fs = require('fs').promises

// Default now config
let defaultConf = {
  version: 2,
  builds: [
    { src: './public/*', use: '@now/static' }
  ],
  routes: [
    { src: '^/(.*)', dest: '/public/$1' }
  ]
}

const getDirs = async path => {
  // Get all files in the current directory
  const files = await fs.readdir(path)

  // Get stats for all files
  const stats = await Promise.all(files.map(async x => ({ name: x, stats: await fs.stat(`${path}/${x}`) })))

  // Keep only dirs : { name: dir_name, stats: stats_of_dir }
  const dirs = stats.filter(x => x.stats.isDirectory())

  // Array of dir names
  return dirs.map(x => x.name)
}


const setup = async () => {
  const dirName = 'src'
  const dirs = await getDirs(dirName)

  dirs.forEach(dir => {
    // Add build path
    defaultConf.builds.push({
      src: `./${dirName}/${dir}/*`, use: '@now/node@canary'
    })

    // Add route (unshift because public should be last)
    defaultConf.routes.unshift({
      src: `^/api/${dir}`, dest: `/${dirName}/${dir}/index.ts`
    })
  })

  console.log(defaultConf)
  return defaultConf
}

module.exports = setup()
```

Finally, here is the final output :
```js
{
  version: 2,
  builds: [
    { src: './public/*', use: '@now/static' },
    { src: './src/dir1/*', use: '@now/node@canary' },
    { src: './src/dir2/*', use: '@now/node@canary' }
  ],
  routes: [
    { src: '^/api/dir2', dest: '/src/dir2/index.ts' },
    { src: '^/api/dir1', dest: '/src/dir1/index.ts' },
    { src: '^/(.*)', dest: '/public/$1' }
  ]
}
```

I can add a check in `read-config-file` to verify the exported data is a js object.

**Comment by rigwild** [comment]
Any comments ?

**Comment by rauchg** [comment]
@rigwild I think we'll hold off until we hear more feedback about this from the community and our customers. We can't take adding _yet another way of defining a deployment's config_ too lightly.

**Comment by vladshcherbin** [comment]
`now.js` file as a config would be awesome (just searched for it in docs).

This would make dynamic configs easy, a big 👍 from me.

**Comment by homerjam** [comment]
> Any comments ?

👍

**Comment by cryptiklemur** [comment]
👍 This should be the standard! Allowing more control over a deployment in a dynamic matter is a feature I'd love to see soon.

@rigwild you do have a merge conflict now

**Comment by rigwild** [comment]
Fixed merge conflicts. Force pushed to revert a fail while doing so !

**Comment by cryptiklemur** [comment]
Test integration failure? 

To add on, I'm looking to make something like this a lot more dynamic and would need this to do so

https://github.com/secretary/now-node-framework

**Comment by rigwild** [comment]
> Test integration failure?
> 
> To add on, I'm looking to make something like this a lot more dynamic and would need this to do so
> 
> https://github.com/secretary/now-node-framework

Feel free to open your own PR as it is not really the same approach as me 😄 

Integration fail occured here, but I don't think that's related to my changes.
https://github.com/zeit/now-cli/blob/1c009266cc077bd7d7db3015d86a108c588612f1/test/integration.js#L80-L87

**Comment by cryptiklemur** [comment]
No need! This PR will allow me to get where I want

**Comment by rigwild** [comment]
Your lib looks nice but I don't think Zeit team will allow to add external now libraries. (I could be wrong)

**Comment by cryptiklemur** [comment]
Trying not to take this PR off track, but I'm not trying to get the Zeit team to do anything except add support for `now.js` config files. My library isn't something that would get baked into zeits offerings

**Comment by homerjam** [comment]
This feature would be really useful. At present I have to use a script to deploy so that I can keep environment variables out of version control (I can't use secrets because these aren't unique to a deployment). If a `now.js` config file were supported then the environment variables could be loaded there rather than a separate script. It should also be possible to add a prevent accidentally deploying without required environment variables and thus breaking production.

**Comment by rigwild** [comment]
I would like some feedback from the Zeit team to know if I close this PR and open an issue instead. I think we need to know what features the community really wants.

**Comment by leo** [comment]
Thank you for this wonderful contribution!

We're really grateful for the inspiration that we were able to derive from projects like these while working the new spec for `now.js`.

We will soon unveil the new specification for the file and announce it publicly. However, I'm going to close this PR as it doesn't match your suggestion.

Thanks a lot! 🙏

**Pull request closed without merging**
