### PR TITLE
Testing Update "undici" package dependency of vercel/node pkg

### PR DESCRIPTION
**Pull request by cb1kenobi**

### CODE REVIEW

**Comment by osdiab** [comment]
@TooTallNate @EndangeredMassa @trek @onsclom @jeffsee55 any chance this or an updated version of it can be considered to resolve #11201 ? Thanks!

**Comment by EndangeredMassa** [comment]
This specific change has already been superseded by other changes to `main`.

**Comment by osdiab** [comment]
@EndangeredMassa  What superseded it? the `vercel` package [still depends on `@vercel/node`](https://github.com/vercel/vercel/blob/7a28972897c031dcc247d3b7fae88ed1f1deaaaf/packages/cli/package.json#L39) and `@vercel/node` package [still depends on a bad `undici` version](https://github.com/vercel/vercel/blob/7a28972897c031dcc247d3b7fae88ed1f1deaaaf/packages/node/package.json#L42), hence our Dependabot going off. Thanks!

**Comment by osdiab** [comment]
And also btw it includes an old version of `@vercel/fun` that also has a compromised `debug` dependency, which has been irking me for months now. Not a big deal end of day but yeah.

**Comment by sudowork** [comment]
Also seeing this show up on our dependabot alerts / don't see that it's been resolved through other changes to main per @osdiab's comment https://github.com/vercel/vercel/pull/10763#issuecomment-2014337782

**Pull request closed without merging**
