### PR TITLE
[examples] Update Remix template for latest.

### PR DESCRIPTION
**Pull request by leerob**
From `create-remix`

### CODE REVIEW

**Comment by leerob** [comment]
Added Vercel Analytics and deployed latest.

https://remix-run-template.vercel.app/
CleanShot 2022-11-05 at 19 52 57@2x

**Comment by leerob** [comment]
Updated: https://vercel.com/templates/remix/remix-boilerplate

**Comment by hafizfarhad** [comment]
...

**Comment by leerob** [comment]
All checks pass, title and labels updated, merging.

**Pull request merged**
