### PR TITLE
Introduced a much cleaner token name

### PR DESCRIPTION
**Pull request by leo**
This makes the CLI align with Now Desktop as per https://github.com/zeit/now-desktop/pull/365.

**BEFORE**

screen shot 2017-09-12 at 12 25 14

**AFTER**

screen shot 2017-09-12 at 12 21 21

### CODE REVIEW

**Review by matheuss — APPROVED** [review]
💅

**Review by TooTallNate — COMMENTED** [review]
It seems kind of weird to be formatting like this on the client-side. Why not fix where the token name is generated?

**Comment by leo** [comment]
We might consider this in the future, if we encounter even more places where we would have to put that logic! 👍

**Comment by matheuss** [comment]
@TooTallNate the token name is generated by the client :v:

**Pull request merged**
