### PR TITLE
[cli] Fix directory arg in createGitmeta for monorepos

### PR DESCRIPTION
**Pull request by hussamkhatib**
### Summary 

The git meta data is read from `.git/config` file. In a monorepo setup, this does not quiet work well because the package/app directory path is provided in the createGitMeta invocation and the not the repository root directory where the config file lies.  

### To reproduce the issue

- Add  debug logs to print the `createGitMeta` output
- Run `pnpm dev deploy --prebuilt --scope=$scope --token=$token --cwd  $path-to-monorepo` 
- You should find that `remoteUrl` will be **undefined** and the deployment in the vercel dashboard isn't **linked** to any branch.

### CODE REVIEW

**Comment by EndangeredMassa** [comment]
@hussamkhatib thanks! We'll take a look.

**Comment by hussamkhatib** [comment]
Hi @EndangeredMassa, I think the Issue is partially fixed. There still seems to be an Issue with git meta data in Github actions though.
I will need to publish my copy of the cli in order to test it in Github actions, Is there any documentation available on how I can publish my copy of the cli ?

**Comment by EndangeredMassa** [comment]
> Hi @EndangeredMassa, I think the Issue is partially fixed. There still seems to be an Issue with git meta data in Github actions though. I will need to publish my copy of the cli in order to test it in Github actions, Is there any documentation available on how I can publish my copy of the cli ?

You can install any package from a github branch:

```
npm install "https://github.com/ORG-OR-USER/REPO.git#BRANCH"
```

If there is more to fix here, feel free to open a new PR. Thanks!

**Comment by hussamkhatib** [comment]
Hey @EndangeredMassa, can you please guide me further on how to go about it ?

If i install the packages as a dependency using the git url, I'm confused how would I execute the scripts ? 
I tried changing dir to`cd node_modules/packages_name && pnpm dev` which din't work.

**Comment by jeffsee55** [comment]
> I think the Issue is partially fixed. There still seems to be an Issue with git meta data in Github actions though.

Can you provide a bit more info about what is fixed and what is not working? Was there a change we made which you can point to?

---

I just tested this out and it worked for me, you could put this into your Github Actions, let me know if that works!

```
pnpm install https://github.com/hussamkhatib/vercel\#git-meta-data
cd node_modules/vercel-monorepo
pnpm install
pnpm run build
cd packages/cli
pnpm run dev build --cwd=/Users/jeffsee/code/website
```
(I'm not sure why/how npm decided to put the module into `vercel-monorepo`, I didn't specify anything there)

**Comment by hussamkhatib** [comment]
> Was there a change we made which you can point to?

I think this PR fixed the original issue
https://github.com/vercel/vercel/pull/11283

> Can you provide a bit more info about what is fixed and what is not working?

The branch name of the deployment doesn't get identified. It resolves to HEAD. 
Screenshot 2024-09-17 at 4 06 00 AM

This was the issue with running the builds outside github action too, because it was trying to access the git metadata from .git dir, but it wasn't looking for it in the root dir in the case of monorepos. This is now fixed.

As a workaround, I am explicitly pointing to a branch 

Before 
```
  steps:
      - uses: actions/checkout@v4
      
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8
```

After 
```
  steps:
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v8

      - uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch-name.outputs.current_branch }}
```



 
---- 

> I just tested this out and it worked for me, you could put this into your Github Actions, let me know if that works!

I was able to run the cli with the steps you mentioned above, but wasn't able to do it in github actions (I din't have the time to check what went wrong, I'm gonna do it tomorrow). I missed the pnpm install in the node_modules initially.

> (I'm not sure why/how npm decided to put the module into vercel-monorepo, I didn't specify anything there)
 
value of name is vercel-monorepo in package.json that's why ?

**Pull request closed without merging**
