### PR TITLE
[cli] redact Extensions

### PR DESCRIPTION
**Pull request by erikareads**

### CODE REVIEW

**Comment by TooTallNate** [comment]
If it's possible, I'm -1 on this. I think it would be interesting to track the value, considering we would only be sending the value _after_ the successful invocation of the extension (i.e. it was definitely invoked as a CLI extension, and not a random typo / non-existing command).

**Review by trek — DISMISSED** [review]

**Comment by erikareads** [comment]
> If it's possible, I'm -1 on this. I think it would be interesting to track the value, considering we would only be sending the value _after_ the successful invocation of the extension (i.e. it was definitely invoked as a CLI extension, and not a random typo / non-existing command).

@trek and I have been discussing this, I would love to know this, but it fails our "we have a known list to compare against" standard for redaction.

**Comment by trek** [comment]
@TooTallNate we worried that if someone wrote their own extension like "send-microsoft-data" or what have you, we now know something privilege.

**Comment by TooTallNate** [comment]
That's what I meant by "if possible". Ok, well, bummer, oh well.

**Review by TooTallNate — APPROVED** [review]

**Pull request merged**
