### PR TITLE
Show aliases for deployments when listing an app

### LINKED ISSUE #1597: Feature request: show aliases in deployment list
If I'm deploying staging and productions version of an app, knowing which one is aliased and where would be awesome, something like:

```
app          url                                inst #    type    state    age    alias               
some-app     some-app-rjprhmyanj.now.sh         0         NPM     READY    39m                      
some-app     some-app-dsbachyilk.now.sh         1         NPM     READY    3h                       
some-app     some-app-mgquqhfzvp.now.sh         1         NPM     READY    7d     staging.app.com     
some-app     some-app-rjprhmyanj.now.sh         0         NPM     READY    39m                      
some-app     some-app-dsbachyilk.now.sh         1         NPM     READY    3h     production.app.com  
some-app     some-app-mgquqhfzvp.now.sh         1         NPM     READY    7d                       
```

Even better would be tagging commits in each deployment, so like:

```
app          url                                inst #    type    state    age  alias               commit
some-app     some-app-rjprhmyanj.now.sh         0         NPM     READY    39m                      d84871b
some-app     some-app-dsbachyilk.now.sh         1         NPM     READY    3h                       oiasvje
some-app     some-app-mgquqhfzvp.now.sh         1         NPM     READY    7d   staging.app.com     8hiergf
some-app     some-app-rjprhmyanj.now.sh         0         NPM     READY    39m                      fg8r94n
some-app     some-app-dsbachyilk.now.sh         1         NPM     READY    3h   production.app.com  dn3nvis
some-app     some-app-mgquqhfzvp.now.sh         1         NPM     READY    7d                       viejors
```

### PR DESCRIPTION
**Pull request by arthurdenner**
Closes #1597.

With this PR, when you run `now ls <app>`, we show a new column: `aliases`.

PS: Same work as #1600, just putting in the correct file, since the project was rewritten.

### CODE REVIEW

**Comment by arthurdenner** [comment]
@leo, sorry for bothering, but this PR has any chance of being merged?

I'm asking this because I just updated it to the latest `canary` and found a bug related to the `now ls` command with the `--all` flag. When this flag is provided, the CLI never exits because we call `now.close` before `now.listInstances`.

Before the fix: 
now-ls-bug
After the fix:
now-ls-bugfix

The fix is contained in this PR, but if you're not interested in this feature, I can send a new PR to fix the bug or you fix it yourself (moving the `now.close` call).

**Comment by juliangruber** [comment]
@arthurdenner thank you for creating this pull request! I see it is quite old unfortunately, but should still be mergeable. What I'm curious about is if anyone still has interest in merging it? The downside is that it will be using more screen estate.

**Comment by arthurdenner** [comment]
@juliangruber, thanks for replying to this PR, I was thinking about closing it a few days ago. :sweat_smile:

Even though the issue that originated this PR is closed because the author is no longer interested in the feature, I think it's a nice and simple addition and it's not a big deal in terms of screen space (is it common to use more than one alias per deployment?).

But if it doesn't interest to anyone else, feel free to close it.

**Comment by juliangruber** [comment]
@arthurdenner Thank you for the context! I've labeled this with `needs community feedback` for now, let's see if more people are interested in this 🙏

**Comment by paul-sachs** [comment]
I'm personally very interested in this feature. I use aliases to provide a reliable naming convention for my deployments, and i'd like to programmatically (via a bot) remove deployments. I haven't currently found another way to do it without running ls to get the deployment via the alias. Unless i'm missing some hidden command.

**Comment by revolunet** [comment]
This is useful for me thanks, it gives more visibility over your "infrastructure" state

**Comment by arthurdenner** [comment]
@juliangruber, will this get merged or should I close the PR?

It's been open for 8 months now if you count the original PR. :sweat:

**Comment by juliangruber** [comment]
Sorry, I'm not maintaining this repo any more. cc @leo

**Comment by arthurdenner** [comment]
Sorry for those who were interested in this but I closed the PR after almost one year without any response from the ZEIT team.

**Pull request closed without merging**
