### PR TITLE
Add new `output` helper functions

### PR DESCRIPTION
**Pull request by TooTallNate**
* Consistently style the opening `>` as grey
 * All logging goes to stderr (any line that beings with `>`).
   No more cases of accidentally forgetting to check `if (!quiet)` since
   its going to stderr anyways. In fact I'd like to remove `quiet` soon.
 * You instantiate the output helper with "debug mode", so that `if (debug)`
   is not constantly being copy+pasted
 * The `time()` function accepts a Promise or async function and wraps it
   with `console.time()` and `timeEnd()`, and passes through the return value.
   There is no way to typo the label since it is only specified once,
   and no way to forget to call `timeEnd()`, which was happening in a few
   cases which are now fixed.

I've only refactored enough for `now deploy` at the moment, but I'll continue refactor other commands once we land this one.

**Before:**

screen shot 2018-02-27 at 12 41 49 pm

**After:**

screen shot 2018-02-27 at 12 42 11 pm

### CODE REVIEW

**Comment by matheuss** [comment]
Amazing @TooTallNate 👏 

However, unless we changed our guidenides (which I don't think we did, cc @evilrabbit @rauchg), the `>`should always have the same color as the "log type". For example, it should be cyan for `> Ready`, yellow for `> Warning`, etc.

**Comment by TooTallNate** [comment]
It's confusing and ugly to me, if that is the case. It's also _not_ consistent if it is the case. See the "Warning!" in the Before screenshot has a white `>`.

**Review by Qix- — APPROVED** [review]
lgtm, thanks @TooTallNate :raised_hands:

**Review by leo — APPROVED** [review]
👌

**Pull request merged**
