### PR TITLE
Fix broken windows clipboard access (fixes #564)

### LINKED ISSUE #564: Copying url to clipboard doesn't happen on windows
I think this is because windows doesn't returns undefined for `process.stdout.isTTY`

### PR DESCRIPTION
**Pull request by rivy**
* simple upgrade to fix windows clipboard access

### CODE REVIEW

**Comment by juliangruber** [comment]
closes #564

**Comment by juliangruber** [comment]
Hey @rivy, thanks for submitting this! Could you please take a look at the failing integration tests?

**Comment by rivy** [comment]
It's not an actual "fail". It looks like it's being tested under my CircleCI account (free version) which doesn't have a MacOS (paid only) plan. That causes the "fail" for "test-integration".

I expect that if you test it under your CircleCI, it should pass.

But, I'm not sure why the PR here would show testing from my account instead of your account.
😕

**Comment by rivy** [comment]
@juliangruber , any forward progress here?

**Comment by rivy** [comment]
@TooTallNate , mergeable?

**Comment by juliangruber** [comment]
cc @leo ^

**Comment by rivy** [comment]
# ☠️

**Pull request closed without merging**
