### PR TITLE
[tests] fix linting errors on yarn lint

### PR DESCRIPTION
**Pull request by nimish-gupta**
Before this PR 
https://www.dropbox.com/s/uirtr9f6jqsfmuv/Screenshot%202020-04-28%2015.30.08.png?dl=0

After the PR
https://www.dropbox.com/s/zb1tkaadnta0h8v/Screenshot%202020-04-28%2016.07.06.png?dl=0

### CODE REVIEW

**Comment by nimish-gupta** [comment]
Created this PR, because on `yarn lint`, there were some linting errors, just fixed those one.

**Comment by nimish-gupta** [comment]
In failing tests `NOW_TOKEN` seems to be missing, how to resolve that?

**Review by styfle — APPROVED** [review]
Thanks!

**Comment by nimish-gupta** [comment]
> Thanks!

Welcome :)

Hey @styfle can you tell me about the NOW_TOKEN variable it seems to be throwing error in the checks?

**Comment by styfle** [comment]
CI won't run the tests because you're not part of the org. You can run locally by using the token in your from `~/.now/auth.json`.

**Pull request merged**
