### PR TITLE
[now-cli] Add `now build` command to allow running builds locally

### LINKED ISSUE #2614: Add `now build` command
This command will allow replicating the production behaviour 100% for testing. No testing, no development watching interface, just production.

### PR DESCRIPTION
**Pull request by ijjk**
This adds initial support for now build to hopefully make debugging easier. It runs the builds in the same process so we can pass custom environment variables to debug faster and we should be able to link builders in .now/builders to test them similar to linking them in NOW_BUILDER_CACHE_DIR='../.now-dev' to debug them with now dev

Closes #2614
Re-opening from #2791 as discussed

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
I reviewed this in #2791. Any reason it wasn't merged? Is it still a WIP?

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
希望

**Comment by iwaki710** [comment]
これからも宜しくお願い致します。

**Comment by iwaki710** [comment]
これからも宜しくお願い致します。

**Pull request closed without merging**
