### PR TITLE
[all] Update TypeScript to v3.9.3 and regenerate `yarn.lock` file

### PR DESCRIPTION
**Pull request by TooTallNate**
To fix GitHub Dependabot security alerts. See: https://github.com/vercel/vercel/network/alerts

Screen Shot 2020-06-03 at 1 36 50 AM

Also updates "typescript" to `3.9.3` for all packages, which is necessary because a downstream dependency is using syntax that requires a newer version of TypeScript.

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
I think we’ll want to change the tsconfig.json files target from esnext to es2018 or es2019 so that we can take advantage of optional changing and other features available in TS. Otherwise we might break older versions of node.

**Comment by TooTallNate** [comment]
@styfle Well we specify `engines >= 10` in the `package.json` and we test Node 10 and 12. So I think we're good? Which `tsconfig.json` file are you talking about specifically?

**Comment by styfle** [comment]
@TooTallNate See how these are using `esnext` https://github.com/vercel/vercel/blob/8ec8affe29e49c27c437d6d74daa8a4f343fce94/packages/now-python/tsconfig.json#L16

This worked fine with the older TS because there was no feature of TS that wasn't implemented in Node 10. But now that there is a newer version of TS, there are some features so we need to downlevel by setting target.

**Comment by styfle** [comment]
Ok I think we can merge because if there are bugs with downleveling, our Node 10 tests will catch it 👍

**Review by styfle — APPROVED** [review]

**Review by AndyBitz — APPROVED** [review]

**Pull request merged**
