### PR TITLE
Allow credit card numbers to be pasted with `now cc add`

### PR DESCRIPTION
**Pull request by mike-engel**
This fixes a bug (#317) where, when pasting a credit card, it would print the
number correctly, but also append too much placeholder. When hitting
enter, backspace, or another number, it would begin printing (and
formatting) `undefined`. This adds a special case where the CC will be
formatted to account for spaces when comparing against the length of the
existing value or placeholder.

My testing with pasting a *full* cc number and with manually entering a credit number worked.

If I missed anything or this doesn't follow formatting, please let me know and I'll make the fixes asap!

### CODE REVIEW

**Comment by leo** [comment]
@matheuss You on this?

**Comment by leo** [comment]
Just tested it locally. Works perfectly! ❤️

**Comment by leo** [comment]
Thanks a lot!

**Comment by mike-engel** [comment]
Happy to help, thanks @leo 😄

**Pull request merged**
