### PR TITLE
Updated sync calls

### PR DESCRIPTION
**Pull request by NikxDa**
Updated sync calls to be awaited async calls.

### CODE REVIEW

**Comment by rauchg** [comment]
In this case they were purposefully sync to avoid race conditions when committing configuration changes (i.e..: making change changes atomic)

**Comment by NikxDa** [comment]
Oh alright, I didn't have any such conditions in mind. Thanks!

**Comment by rauchg** [comment]
Thank you for the contribution!

**Comment by leo** [comment]
If you're interested in contributing a comment in the code, that would be lovely!

**Pull request closed without merging**
