### PR TITLE
fix: avoid block user use global typescript

### PR DESCRIPTION
**Pull request by bluelovers**

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
What is this fixing? Can you add a test that fails without this PR?

**Comment by TooTallNate** [comment]
What is this fixing exactly?

**Comment by bluelovers** [comment]
```json
{
  "compilerOptions": {
    "target": "ES2019",
    "alwaysStrict": true
  }
}
```

```ts
let b;

export let a = b ??= true;
```

global install typescript@next
local install vercel

```json
  "scripts": {
    "test": "ts-node index.ts",
```

image

**Comment by TooTallNate** [comment]
It's not going to work with a globally installed `typescript`. You need to install it as a local dependency instead (`yarn add --dev typescript`).

If you can create a repository that demonstrates your issue then we can take a look and perhaps send a PR to show you the fix.

**Pull request closed without merging**
