### PR TITLE
[now-cli] Deprecate `--name` and now.json `name` property

### PR DESCRIPTION
**Pull request by lucleray**
`--name` is replaced by either:
- linking the folder to a project
- `NOW_ORG_ID` and `NOW_PROJECT_ID` environment variables

image

### CODE REVIEW

**Review by AndyBitz — APPROVED** [review]

**Comment by dehamzah** [comment]
can you give some examples how to do the old `--name` with this new release?

**Comment by fynncfchen** [comment]
It cause my BitBucket pipeline failed....
Is there any workaround here?

**Comment by lucleray** [comment]
@dehamzah @fynncfchen 

The `--name` flag can still be used. It has been deprecated but not removed.

Also note that you can keep skip the questions by providing the [`--confirm` flag](https://zeit.co/docs/now-cli#commands/now/unique-options/confirm) to `now`.

In your cases, I believe you can use `now --name <name> --confirm` to run Now CLI in continuous integrations environments.

**Comment by fynncfchen** [comment]
Thanks for the advice, but I'm curious that if I provide the `--confirm` flag, the project will also set to the `<name>` what I'm provide using the `--name` flag, or the folder name?

**Comment by lucleray** [comment]
@fynncfchen The project name will be inferred from `--name`, the `name` property in `now.json`  and the folder name in this order.

**Comment by fynncfchen** [comment]
That'll be perfect! Thanks a lot!

**Comment by thedevdavid** [comment]
Hey,
I have a NextJS app with 3 separated environments. (Dev, Staging, Prod)
Until now, I used with 3 separate now.json files to deploy the 3 stages. Looking like this one:
```
now.staging.json
{
    "version": 2,
    "public": false,
    "scope": "myteam",
    "name": "myapp-staging",
    "builds": [
        {
            "src": "next.config.js",
            "use": "@now/next@canary"
        }
    ],
    "build": {
        "env": {
            "ALGOLIA_APP_ID": "@staging_algolia_app_id",
            "FIREBASE_APP_ID": "@staging_firebase_app_id",
            "etc": "@etx"
        }
    },
    "rewrites": [
        { "source": "/", "destination": "/" },
        { "source": "/(.+)", "destination": "/$1" }
    ]
}
```

And deployed the stages like: `now -A now.staging.json --prod`
How can I do this with the new Project Linking?

**Comment by Ynniss** [comment]
We use almost the same workflow as @DLevai94 (with CI to deploy, regarding whether it's pre-prod or production)
Would like to know as well,  if there's  an alternative using **Project linking**.

On our side, we actually "freezed" the now version used on the CI, to prevent breaking changes incoming (e.g suppression of property name) and just keeped the name property on our now_*environment*.json files

Here's how it looks like on our CI:

```
now-deploy:
  stage: deploy
  before_script:
    - apk add yarn
    - yarn global add now@17.0.3
  tags:
    - docker-build
  script:
    - now -t $NOW_TOKEN --scope $TEAM --local-config now.preprod.json --confirm --prod
  only:
    - develop
```

**Pull request merged**
