### PR TITLE
[tests] Fix dev-macos-tests

### PR DESCRIPTION
**Pull request by nimish-gupta**

### CODE REVIEW

**Comment by nimish-gupta** [comment]
This can be due to this https://github.community/t5/GitHub-Actions/Can-t-view-log-for-failed-action/m-p/37795

As in the `test-integration-unit.yml` `if` condition is used for installing hugo
```
 - name: Install Hugo
        if: matrix.os == 'macos-latest'
        run: curl -L -O https://github.com/gohugoio/hugo/releases/download/v0.56.0/hugo_0.56.0_macOS-64bit.tar.gz && tar -xzf hugo_0.56.0_macOS-64bit.tar.gz && mv ./hugo packages/now-cli/test/dev/fixtures/08-hugo/
```

**Comment by nimish-gupta** [comment]
Also getting this error
`Failed `test.before`
Error: Failed to create test deployment. Did you forget to set NOW_TOKEN?`
This env variable should be set under GitHub action right?

**Comment by nimish-gupta** [comment]
Tests can also be broken due to timeout issue, which is showing more than 30 minutes in the latest commit https://github.com/zeit/now/runs/626111204

Right now it is set to `30 minutes`.
```
    name: Dev
    timeout-minutes: 30
```

**Comment by nimish-gupta** [comment]
I have to, again and again, create the `NOW_TOKEN` for tests to past, if i don't do that, create user throws an error.
```
const createUser = async () => {
  await retry(
    async () => {
      const location = getConfigPath();
      token = await fetchTokenWithRetry();

      if (!fs.existsSync(location)) {
        await createDirectory(location);
      }

      await fs.writeJSON(getConfigAuthPath(), { token });

      const user = await fetchTokenInformation(token);

      email = user.email;
      contextName = user.email.split('@')[0];
      session = Math.random()
        .toString(36)
        .split('.')[1];
    },
    { retries: 3, factor: 1 }
  );
};
```

NOW_TOKEN keeps on expiring after I run the tests.

**Comment by lucleray** [comment]
@nimish-gupta The token is "removed" because the tests are logging out the user. You can disable that by commenting out these lines when running the tests:
https://github.com/zeit/now/blob/9083b558f0c90a6d440b9df10c44c5b0c5a099f1/packages/now-cli/test/integration.js#L199-L209

**Comment by nimish-gupta** [comment]
> The token is "removed" because the tests are logging out the user. You can disable that by commenting out these lines when running the tests:

Does the now_token, which is present during CI, keeps on expiring? If yes then these [tests](https://github.com/zeit/now/runs/629326774) should either fail because the Zeit API will return 403 or I am missing something here. @lucleray

**Comment by lucleray** [comment]
@nimish-gupta During CI, a new token is retrieved for every run. The token you pass as `NOW_TOKEN` doesn't expire, but are removed when the tests "log" out.

**Comment by nimish-gupta** [comment]
> @nimish-gupta During CI, a new token is retrieved for every run. The token you pass as `NOW_TOKEN` doesn't expire, but are removed when the tests "log" out.

@lucleray  So lemme explain what I am doing. I am generating a token from [here](https://www.dropbox.com/s/x0bwzwoisr0wtke/Screenshot%202020-04-30%2015.57.17.png?dl=0). I store this token value under `NOW_TOKEN`. If I use this token to hit, using postman, `https://api.vercel.com/www/users` it is returning my info.  But after I run the tests using `yarn test-integration-cli` and then again hitting it through postman it is throwing [this](https://www.dropbox.com/s/lp7ash3d3elxe1j/Screenshot%202020-04-30%2015.56.36.png?dl=0). I think it can be due to https://github.com/zeit/now/blob/9083b558f0c90a6d440b9df10c44c5b0c5a099f1/packages/now-cli/src/commands/logout.ts#L90-L110

**Comment by nimish-gupta** [comment]
In the cli integration tests, login is waiting for manually clicking on the email for authentication.

http://g.recordit.co/DtkSaDvzOL.gif

Above^ thing is happening on my localhost, can this be the reason for tests to get failed? @lucleray?

**Comment by styfle** [comment]
Closing since there is no file changed here

**Pull request closed without merging**
