### PR TITLE
[BUG-FIX] team invite ignored scope error

### LINKED ISSUE #2139: `now teams invite` --scope not working
When `now teams invite` is used, it will invite guest into the default scope even with --scope [slug] passed as a parameter.

My default team is *BBI* (I did got the team slug wrong initially):

image

If I switched to my personal account as scope:

image

What should have happend:
1. if used with --scope [slug], and [slug] is not defined, return error
2. if used with --scope [slug], and [slug] is a user, return error
3. if used with --scope [slug], and [slug] is a team, invite!

### PR DESCRIPTION
**Pull request by wiiiimm**
fixes #2139

### CODE REVIEW

**Review by leo — CHANGES_REQUESTED** [review]
We need to prevent it for `switch` and `create`.

**Comment by wiiiimm** [comment]
@leo i don't think you do, as switch doesn't look at scope / current time and create operates on the username level

PS: I have already tried to do `now teams switch` and `now teams create` with `--scope [teamslug]` and nothing breaks

PPS: if you want, I can add a check for `subcommand` if targetCommand is team, it just seem unnecessary.

**Comment by leo** [comment]
@williamli The reason why `teams` was excluded before is that `--scope` defeats the purpose of `create` and `switch`:

- It does not make any sense to invoke `create` using a selected scope, because team creating doesn't depend on a scope - it is independent from scopes.

- It does not make any sense to invoke `switch` using a scope because that's what the command is for: Selecting a scope.

**Comment by leo** [comment]
> as switch doesn't look at scope / current time and create operates on the username level

This is false, by the way. That's the main purpose of `switch`: Reading and writing `currentTeam`.

**Review by leo — CHANGES_REQUESTED** [review]
See above

**Review by leo — CHANGES_REQUESTED** [review]
It says `invite` twice

**Review by leo — CHANGES_REQUESTED** [review]
You're missing `create` @williamli

**Comment by wiiiimm** [comment]
@leo what is `create`?

**Comment by wiiiimm** [comment]
@leo you mean `now teams create` which is the same as `now teams add`?

what about it? as of now, `create`, `add`, `ls`, `switch` (anything but `invite`) will not be affected by `--scope`

**Comment by leo** [comment]
Oh, you reversed the logic. Sounds great too.

**Review by leo — APPROVED** [review]

**Pull request merged**
