### PR TITLE
[examples] Change hugo template to one that works with older version

### PR DESCRIPTION
**Pull request by leerob**
This template looks overall better, _and_ supports the min Hugo version we have in the build container.

https://hugo-leerob-now-examples.vercel.app

It's also way more minimal than the previous example.

image

### CODE REVIEW

**Review by styfle — APPROVED** [review]
Sounds good, don't forget to deploy the example after merging 👍

**Comment by styfle** [comment]
@leerob The links on the main page (https://hugo-leerob-now-examples.vercel.app) are all examples that 404. Maybe they should link to other hugo pages?

**Comment by leerob** [comment]
@styfle good idea - fixed in the latest commit -> https://hugo-template.vercel.app/

**Review by TooTallNate — APPROVED** [review]

**Review by styfle — APPROVED** [review]
Thanks!

**Pull request merged**
