### PR TITLE
typo

### PR DESCRIPTION
**Pull request by slightlyoffbeat**
Possible typo (or perhaps a term I'm not familiar with)

### CODE REVIEW

**Comment by leo** [comment]
I believe this wasn‘t a typo. @rauchg? @jamo?

**Comment by leo** [comment]
Yep. Not a typo. Thanks though! 😊

**Comment by jamo** [comment]
Yup; not a typo - the change is atomic.

**Comment by slightlyoffbeat** [comment]
Well, color me embarrassed. Thanks all

**Pull request closed without merging**
