### PR TITLE
[cli] Fix `vc build` with nested app dir

### PR DESCRIPTION
**Pull request by AndyBitz**
### Related Issues
We'll have to use `appDir` instead of `distDir`, because the paths are relative to it.

#### Tests

- [ ] The code changed/added as part of this PR has been covered with tests
- [ ] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

### CODE REVIEW

**Review by leo — COMMENTED** [review]
Pinged Jared for a review, since `git blame` says he introduced those lines.

**Review by jaredpalmer — APPROVED** [review]
Lgtm.

**Review by leo — COMMENTED** [review]
@AndyBitz I think only you can remove Nate's required review — I can't.

**Comment by AndyBitz** [comment]
@leo I cannot, but I can still merge. But, I'm currently verifying that this does fix all problems

**Pull request merged**
