### PR TITLE
Support `now alias` reading `config.alias`

### PR DESCRIPTION
**Pull request by remy**
- [x] PR ready?

Reads the last deployment and will automatically alias to the package.json's config.alias property
#### What's this PR do?

Add support for reading the default alias target from a `package.json`'s `config.alias` property.

Running `now alias` will look for the latest deployment (and throw if there isn't one) and then look for the `config.alias` to allow the user to shortcut the current `now alias <deployment> <target>`.

Related ticket: https://github.com/zeit/now/issues/68

### CODE REVIEW

**Comment by leo** [comment]
Looks good to me, thanks! 😊 

The only thing that I would criticize is that we're using the `config.alias` property from `package.json`. Shouldn't we call it `now.alias`?

To me, `config` seems a little too broad and it might conflict with other packages.

**Comment by rauchg** [comment]
`now.alias` is the way to go. Also, an `--alias` flag would be nice. Finally, we should document later on that it's recommended that you use a internal `now.sh` alias, not your definitive alias, when using this setting, to avoid unexpected downtime in case you made a mistake with your deployment!

**Comment by remy** [comment]
Agree on the `config.now.alias` - I wasn't totally happy with the broad `config.alias` too.

I don't quite understand what `--alias` would be used for? Given the CLI command (suggested) would be `now alias --alias` …?

Lastly, I didn't quite follow the point about internal aliases…but it seemed important. Is that more of a documentation process for Team Zeit?

**Comment by rauchg** [comment]
```
now --alias woot
```

It'd be a modifier upon deployment. Deploys and then aliases to `woot.now.sh`. In general we tend to keep a 1:1 correlation between config flags and modifiers.

The reason the internal alias is smart is that let's say you're operating `remy.com`. You could be 100% confident about the deployment you're about to make, but at the last instant you forgot a critical semi-colon.

The beauty of the now model is that every time you deploy you're "staging", even though the links are production-ready. It allows you to verify the deployment prior to upgrading it via an alias.

So, my humble suggestion would be that instead your default alias could be, for the case above, `remy.now.sh`. 

When you check that `remy.now.sh` looks good, you move forward with the definitive `alias`.

Obviously, there are a huge number of people who are more risk-averse and will want to move forward with the definitive alias, which is why I simply suggested we make this a suggestion in the documentation. And yes, that was meant as a note for ourselves, not for that pull request.

Thank you! 🎉

**Comment by rauchg** [comment]
By the way, the modifier might not be needed because I just realized you are only reading the config upon `now alias` without parameters, instead of just `now`.

I actually think that's really smart and I love this!

Maybe we should add an example to the `now alias` help. Also, when `now alias` is run with no parameters, the error message should be more explicit. Something like:

```
> Error! Missing alias source and target, and no `alias` setting found!
> <Help here which talks about the setting as well>
```

**Comment by remy** [comment]
@leo / @rauchg re `now.alias`, do you mean to add `now` as a root property off the `package.json` or that it should live under the `config` property? I had assumed the later since that's the convention for extra config stuff…(I'm making the changes now, so let me know).

**Comment by leo** [comment]
@remy It should be `now.alias` in the file (also never heard of that `config` convention). 😊

**Comment by remy** [comment]
@leo was based on this https://docs.npmjs.com/files/package.json#config

**Comment by leo** [comment]
@remy Ahh, interesting! 😊 It's a little weird though, because - to me - it looks like most packages out there have their own `package.json` property. Not sure...

But let's go with `now` instead, since that's what most packages are doing atm.

**Comment by remy** [comment]
Yeah, I had seen that in your own `package.json`, like the `xo`. I'm personally not keen on polluting the root like `xo` is doing, but I'm happy to take what you prefer (no judgement, I'll still use this property on my own projects 😄).

Go with `root/now.alias`, yeah?

**Comment by remy** [comment]
I've moved the reading of the config. This is _technically_ ready for review/merge. 

I'd love to get some proper end to end tests in place, probably using something like spies and proxyquire ala https://github.com/remy/now-realias/blob/master/test/index.test.js. But I'm taking my initial cues from the existing code, so hopefully this is all good :)

**Review by leo — APPROVED** [review]

**Comment by leo** [comment]
@remy Thanks a lot! ❤️

**Comment by remy** [comment]
Quick reply as I'm on the move.

`now.alias` - sure, wanted to check this anyway.

Not sure what the `--alias` would be for.

Also, I'm sure you're right, but can you explain the bit about internal
aliases again? I'm not sure I totally followed but it seemed to be
important!

**Comment by sedubois** [comment]
Thanks for this 😊 But I didn't figure out how to use, it could help to document somewhere? My `package.json` looks like this:

```
{
  ...,
  "now": {
    "alias": "blah"
  }
}
```

But when running `now`, I don't get the deployment aliased.

And yes, probably a `now --alias blah` would be quite helpful. 

Also, without needing to specify any extra config, `now` could set an alias using the package name directly?

And it would be great to see this alias when running `now ls` instead of needing to run `now alias ls`?

**Comment by remy** [comment]
You need to run `now alias`.

The idea being you don't want to automatically alias as you deploy since
you're likely to want to check your staged deployment.

However, if you're a little more fast and loose, you can do `now && now
alias`

**Comment by sedubois** [comment]
Wonderful, thanks.

**Comment by sedubois** [comment]
An automatic aliasing could still make sense, just using a staging name: `now && now alias blah-staging`.

And `now --alias` would still be great so that while the `now` command runs, it prints the alias URL directly, instead of the cryptic version.

**Comment by remy** [comment]
It's not so much cryptic, but more keeping the tools composing rather than having one entry/command doing multiple tasks (which I'd argue is actually more cryptic). But still, this was just my PR not my project, just trying to stay true to the current ethos of the code and project.

**Pull request merged**
