### PR TITLE
[now-cli] Print error during install for unsupported Node version

### LINKED ISSUE #3866: Now Dev Crashes on Node 8
When running `now dev` on node 8.6, it crashes with a very cryptic error. It should check the node version cleanly if there's a requirement.

```
kpffl % now dev                                                                                     (master) kpffl 
/usr/local/Cellar/now-cli/17.0.4/libexec/lib/node_modules/now/dist/index.js:2
require('./sourcemap-register.js');module.exports=function(e,t){"use strict";var n={};function __webpack_require__(t){if(n[t]){return n[t].exports}var r=n[t]={i:t,l:false,exports:{}};e[t].call(r.exports,r,r.exports,__webpack_require__);r.l=true;return r.exports}__webpack_require__.c=n;function startup(){return __webpack_require__(4165)}t(__webpack_require__);return startup()}([,,,,,,,,,,,,,,,,function(e,t,n){"use strict";var r=this&&this.__importDefault||function(e){return e&&e.__esModule?e:{default:e}};Object.defineProperty(t,"__esModule",{value:true});const i=r(n(4859));function arrayMove(e,t,n,r,i){for(let o=0;o<i;++o){n[o+r]=e[o+t];e[o+t]=void 0}}function pow2AtLeast(e){e=e>>>0;e=e-1;e=e|e>>1;e=e|e>>2;e=e|e>>4;e=e|e>>8;e=e|e>>16;return e+1}function getCapacity(e){return pow2AtLeast(Math.min(Math.max(16,e),1073741824))}class Deque{constructor(e){this._capacity=getCapacity(e);this._length=0;this._front=0;this.arr=[]}push(e){cons

SyntaxError: Unexpected token *
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
kpffl %                                                                                             (master) kpffl
kpffl % nvm use                                                                                     (master) kpffl 
Found '/Users/XXXXX/Documents/Projects/kpffl/.nvmrc' with version <13.8.0>
Now using node v13.8.0 (npm v6.13.6)
kpffl % now dev                                                                                     (master) kpffl 
Now CLI 17.0.4 dev (beta) — https://zeit.co/feedback
> Ready! Available at http://localhost:3000
```

### PR DESCRIPTION
**Pull request by styfle**
Fixes #3866 

### Output
```
> now@18.0.0 preinstall /usr/local/lib/node_modules/now
> node ./scripts/preinstall.js

> Error! Detected unsupported Node.js version.
Expected ">= 10" but found "8.10.0".
Please update to the latest Node.js LTS version to install Now CLI.
```

### CODE REVIEW

**Comment by TooTallNate** [comment]
Doesn't `engines.node` in package.json already return an error?

**Comment by styfle** [comment]
@TooTallNate Only when you use `npm i -g --engine-strict now`.

See my comment here: https://github.com/zeit/now/issues/3866#issuecomment-594209999

**Comment by TooTallNate** [comment]
Oh ok, cause `npm`… `yarn` errors by default I believe.

**Comment by styfle** [comment]
Yep, that is what my comment says 😄

**Review by leo — APPROVED** [review]

**Pull request merged**
