### PR TITLE
Replace standard with XO

### PR DESCRIPTION
**Pull request by jfmengels**
This continues the work started in https://github.com/zeit/now/pull/69.

I disabled certain rules because they were too present at the moment, so this could be done at a later time.

There was a lot of manual fixes, so there are obviously chances for breakage. The test coverage is not that great, so it won't help much.
Let me know if you want me re-do the work in a way that will be easier to read, or on a step by step basis.

I kept the version at 0.16 at the moment, as there is I think a bug in XO ([I filed an issue here](https://github.com/sindresorhus/xo/issues/156) if you want to follow it) when you want to ignore a subdirectory (`test/_fixtures`) while also running on the parent directory (`test/`) and you changed the file extensions to lint to "no-extension". The files in `bin/` are not linted by default because they do not have a `.js` extension.

### CODE REVIEW

**Comment by jfmengels** [comment]
The test that is failing seems flaky. I have the same error locally sometimes.

**Comment by leo** [comment]
Ahhh! Yea, same for me. Seems to be inconsistent. Thank you! 😊 

I'll check this with the team, not sure if they want to merge in sth from our private now repo first.

**Comment by jfmengels** [comment]
I'm guessing you chose to merge that thing first :smile:
Will see when I can do the rebasing, or should I wait more?

**Comment by leo** [comment]
@jfmengels We're currently merging the private now stuff onto the public repo... 😄

Sorry for that, but you'll have to wait a few minutes. After you saw an announcement on our Twitter account, feel free to rebase (or create a new PR)! 😊

**Comment by jfmengels** [comment]
> Sorry for that, but you'll have to wait a few minutes.

I will not work on it before this evening, so no worries ;)
Looking forward to the announcement :)

**Comment by leo** [comment]
I'm on this!

**Comment by jfmengels** [comment]
Sure. Let me know if you want help or me to take over again.

**Comment by leo** [comment]
Done! 😊 Thanks for your help though. 🚀

**Pull request closed without merging**
