### PR TITLE
[cli] Support configuring package manager version

### LINKED ISSUE #8044: Vercel doesn't seem to run pnpm with v7 in CI
pnpm changed from `lockfileVersion: 5.3` to `lockfileVersion: 5.4` in v7.

I redeployed without cache but there is still a warning in the pipeline like this:

```
08:37:34.173 | Installing build runtime...
08:37:36.081 | Build runtime installed: 1.907s
08:37:37.425 | No Build Cache available
08:37:37.735 | Running "install" command: `pnpm install`...
08:37:38.329 | Scope: all 7 workspace projects
08:37:38.448 | WARN  Your pnpm-lock.yaml was generated by a newer version of pnpm. It is a compatible version but it might get downgraded to version 5.3
08:37:38.449 | Lockfile is up-to-date, resolution step is skipped
```

pnpm v6 and v7 differs quite a bit so installing with the older version could lead to issues.

***

UPDATE on 7th August: When fixing the issue, it would be great if the Vercel team could make sure not only to check for a string of `lockFileVersion: 5.4` but rather if the string includes that part. This is important because the value can also be `lockfileVersion: 5.4-inlineSpecifiers` when `use-inline-specifiers-lockfile-format` is enabled with was part of this release: `https://github.com/pnpm/pnpm/releases/tag/v7.7.0

### LINKED ISSUE #8342: Cannot configure package manager versions to use when deploying apps
It doesn't seem like we can configure a package manager version when deploying and building apps.

### PR DESCRIPTION
**Pull request by verbose117**
This PR adds support configuring `packageManager` version inside `package.json` and use them as the version while deploying.

### Related Issues

> Fixes #8342
> Related to #8272, #8044  

#### Tests

- [x] The code changed/added as part of this PR has been covered with tests
- [x] All tests pass locally with `yarn test-unit`

#### Code Review

- [x] This PR has a concise title and thorough description useful to a reviewer
- [x] Issue from task tracker has a link to this PR

### CODE REVIEW

**Review by styfle — CHANGES_REQUESTED** [review]
This feature is already supported

https://vercel.com/changelog/corepack-experimental-is-now-available

**Comment by verbose117** [comment]
> This feature is already supported
> 
> https://vercel.com/changelog/corepack-experimental-is-now-available

Ok, so is this PR relevant anymore?

**Comment by EndangeredMassa** [comment]
I think we can close this. Check out corepack support and let us know if it doesn't do what you need. Thanks!

**Comment by verbose117** [comment]
Okay, great 👍!

**Pull request closed without merging**
