### PR TITLE
[node] Move `@types/content-type` to dev dependency

### PR DESCRIPTION
**Pull request by TooTallNate**
`@types/content-type` is only needed at build time.

### CODE REVIEW

**Review by styfle — DISMISSED** [review]

**Review by cb1kenobi — CHANGES_REQUESTED** [review]
Are you sure about this? This reverts a fix PR from the other day? https://github.com/vercel/vercel/pull/10274

**Review by trek — COMMENTED** [review]
Dang @cb1kenobi beat me to it.

**Comment by TooTallNate** [comment]
@cb1kenobi It does not. `content-type` is still a regular dependency. This only applies to the TypeScript types package.

**Review by cb1kenobi — APPROVED** [review]
This is epic! And I can't read.

**Pull request merged**
