### PR TITLE
[docs] Suggest removing now.json when Next.js fails

### PR DESCRIPTION
**Pull request by hellojennifertran**
### Related Issues

> Fixes #1
> Related to #2

#### Tests

- [ ] The code changed/added as part of this PR has been covered with tests
- [ ] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
I'm going to defer to @ijjk because I think this entire page needs to be rewritten due to `target: serverless` being removed

**Review by ijjk — COMMENTED** [review]
Is there a related discussion/thread for this?

**Review by ijjk — COMMENTED** [review]
I think we may want to expand on this with some related context or close for now and revisit as just removing `now.json`/`vercel.json` may cause further issues unless we guide towards updating project settings as well

**Comment by EndangeredMassa** [comment]
Closing for now, but feel free to restart this conversation

**Pull request closed without merging**
