### PR TITLE
[docs] Add scripts for changelog and diff

### PR DESCRIPTION
**Pull request by styfle**
This PR puts the instructions from the [wiki](https://github.com/zeit/now/wiki/Creating-a-Release) into code.

I also removed the publishing.md doc since the wiki is the source of truth.

I'll update the wiki once more when this PR is merged.

### CODE REVIEW

**Comment by TooTallNate** [comment]
Code LGTM. This seems like a job for Bash though, IMO.

**Comment by styfle** [comment]
@TooTallNate Right, you said that last time with the `run.js` script too 😄 

By using Node scripts instead of bash, we can support Windows (in the future) with a couple modifications. (the current script assumes you have `grep` and `head` available in the PATH)

**Comment by TooTallNate** [comment]
Not really if we're using Unix commands like `grep`,  pipes and `&&`

**Comment by styfle** [comment]
@TooTallNate I updated the scripts to not use bash. These should work on Windows now 👍

**Review by TooTallNate — APPROVED** [review]

**Pull request merged**
