### PR TITLE
`edge-light` condition interoperability with `vercel dev`

### PR DESCRIPTION
**Pull request by PonomareVlad**
1. [Ref](https://github.com/vercel/vercel/blob/2995781a583a9c6df15f6447667ff7adaa0d3bfd/packages/node/src/index.ts#L179)
2. [Spec](https://runtime-keys.proposal.wintercg.org/#edge-light)
3. [Test](https://github.com/PonomareVlad/VercelEdgeExportsTest)

### CODE REVIEW

**Comment by EndangeredMassa** [comment]
@PonomareVlad can you explain why this is needed and how it works?

I did find https://esbuild.github.io/api/#conditions, which was helpful.

**Comment by PonomareVlad** [comment]
@EndangeredMassa You can test [this repo](https://github.com/PonomareVlad/VercelEdgeExportsTest).

If we deploy it to Vercel, then we see that `edge-light` target is used for modules import.

But, if we run `vercel dev` then we see using `browser` target.

This is inconsistently, and PR should fix that.

Also `development` target improve stack traces readability for dependencies source without minification (if they have that). 🌚

**Review by styfle — DISMISSED** [review]
Looks correct since prod deploys check for `edge-light` since https://github.com/vercel/vercel/pull/9700

We might need to add more conditions here for dev.

cc @TooTallNate

**Comment by cb1kenobi** [comment]
Tests pass: https://github.com/vercel/vercel/pull/10332

**Review by cb1kenobi — APPROVED** [review]

**Comment by cb1kenobi** [comment]
Thank you @PonomareVlad!

**Pull request merged**
