### PR TITLE
[go] Add support for Go 1.20

### PR DESCRIPTION
**Pull request by vedantmgoyal9**

### CODE REVIEW

**Review by cb1kenobi — DISMISSED** [review]
Looks great! Thank you!

Go 1.20 was released Feb 1, 2023: https://go.dev/doc/devel/release#go1.20

**Review by EndangeredMassa — DISMISSED** [review]

**Review by styfle — CHANGES_REQUESTED** [review]
Looks like the URL is incorrect since tests are failing

```
Failed to parse AST for "index.go"
Error: Failed to download: https://dl.google.com/go/go1.20.0.linux-amd64.tar.gz (404)
```

**Comment by vedantmgoyal9** [comment]
cc @EndangeredMassa
 @cb1kenobi @TooTallNate @Ethan-Arrowood @styfle I've made changes

**Comment by cb1kenobi** [comment]
@vedantmgoyal2009 I was testing this and it turns out my example has a `go.mod` where I can specify the Go version to use. If I pick 1.19 or 1.20, the deploy fails. I need some more time to investigate.

**Comment by vedantmgoyal9** [comment]
@cb1kenobi i think it should work now. by any chance, can you prioritize this a little bit? my deployment is dependent on this...

**Comment by cb1kenobi** [comment]
@vedantmgoyal2009 I appreciate your patience.

I did some testing and there is an issue that I haven't dug deep enough to figure out yet.

We support specifying the Go version via the `go.mod` file in the root of your project. Docs: https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/go#go-version.

I [tested](https://github.com/vercel/vercel/pull/9369) a number of scenarios with your latest PR:

| | Build Version | Runtime Version |
| --- | --- | --- |
| no go.mod | 1.20.1 | 1.18.1 |
| empty go.mod | 1.20.1 | 1.18.1 |
| go.mod 1.18 | 1.18.1 | 1.18.1 |
| go.mod 1.19 | 1.19.5 | go tidy error |
| go.mod 1.20 | 1.20.1 | go tidy error |

Regardless of the Go version specified in the `go.mod`, the runtime version is always 1.18.1 as I believe this is controlled by AWS. I will look into this a bit more as this doesn't seem right.

When the version in the `go.mod` is 1.19, the `go mod tidy` error I'm seeing is:

```
Tidy `go.mod` file...
Exec 'go mod tidy'
go: go.mod file indicates go 1.19, but maximum version supported by tidy is 1.18
failed to `go mod tidy`
Go Builder Error: Error: Command failed: go mod tidy
Error: Command failed: go mod tidy
```

I'm not sure what exactly `go mod tidy` does or how it's invoked. I'm investigating this.

Another thing that confuses me is if how does the current `cowsay` test pass on `main`? That test doesn't have a `go.mod`, so it'll build with 1.19.5, but it should use 1.18.1 at runtime and the test expects 1.19.5.

Related, I think we should add 3 new versions of the `cowsay` test that include a `go.mod` with the versions 1.18, 1.19, and 1.20.

As apart of testing this, I noticed that our [docs](https://vercel.com/docs/concepts/functions/serverless-functions/runtimes/go#go-version) state the default Go version is 1.16, which is not true. I'll update the docs as soon as I investigate the other issues.

I'm going to continue to actively investigate these changes. If you have any insight to `go mod tidy` or Go runtime versions on AWS, that would be helpful. Thank you!

**Comment by vedantmgoyal2009** [comment]
> I'm not sure what exactly `go mod tidy` does or how it's invoked. I'm investigating this.

https://github.com/vercel/vercel/blob/70a53515bd12202f895c369504e2d5be6c9469f4/packages/go/go-helpers.ts#L89

**Comment by vedantmgoyal2009** [comment]
https://github.com/vercel/vercel/blob/main/packages/go/go.mod

@cb1kenobi I believe this is what sets the default Go version to be used.

**Comment by vedantmgoyal9** [comment]
> I'm not sure what exactly `go mod tidy` does or how it's invoked. I'm investigating this.

https://github.com/vercel/vercel/blob/70a53515bd12202f895c369504e2d5be6c9469f4/packages/go/go-helpers.ts#L89

@cb1kenobi based on the table, I believe this (https://github.com/vercel/vercel/blob/main/packages/go/go.mod) is what sets the Go version to be used. The comments say that it is used for debugging, but `1.18` is specified here only.

**Comment by cb1kenobi** [comment]
@vedantmgoyal2009 I played around with `go mod tidy` yesterday. It seems it's impossible to get it to "lint" the mod file if the version in the mod file is newer than the version doing the linting. There is a `-e` flag with which will basically ignore any issues and return zero. I dunno if that's a good idea.

Meanwhile, I started playing around with the prebuilding the Go serverless functions. If you do `vc build --prod`, then `vc deploy --prod --prebuilt`, you can get around the `go mod tidy` issue, however it has a runtime error:

```
[GET] /api/fun.go
fork/exec /var/task/handler: exec format error: PathError
null
```

I'll continue to investigate this error as well as figure why the existing tests don't blow up in CI.

**Comment by vedantmgoyal9** [comment]
https://vercel.com/vedantmgoyal2009-s-pro/winget-manifests-manager/HgMYgUfudUx4VnE38GmpQ3knycqK?filter=all

@cb1kenobi How can I give you access to my project? I have got a new error, which I think can be helpful for you.

**Comment by cb1kenobi** [comment]
@vedantmgoyal2009 does your project run locally when running `vc dev --debug`?

I copied the `01-cowsay` to a new directory and it's erroring on me:

```
> [debug] [2023-02-17T18:28:17.683Z] Imported Builder "@vercel/go" from "/Users/chris/code/vercel/packages/go"
pattern ./...: directory prefix . does not contain main module or its selected dependencies
Error: Command failed: go build -o ./vercel-dev-server-go ./...
```

**Comment by vedantmgoyal9** [comment]
> @vedantmgoyal2009 does your project run locally when running `vc dev --debug`?

Nope.

**Comment by cb1kenobi** [comment]
@vedantmgoyal2009 Are you by chance on a Mac with Apple Silicon?

**Comment by vedantmgoyal9** [comment]
Sadly, no. I applied for https://www.macstadium.com/opensource but received no response 😭

**Comment by cb1kenobi** [comment]
@vedantmgoyal2009 ok, I'm investigating Go distribution architectures. I have been running into issues and that's when I found out I have been testing 1.19.6 arm64 (which is correct for M1 mac) as well as 1.20.1 amd64, but that seemed to also work!?

So now that I know my machine is a wonky state, I reinstalled 1.19.5 arm64 and still running into issues. `go build` fails because it can't find the entrypoint file or `go.mod`. I don't have a `go.mod` in my test project and one isn't generated, so now I'm trying to figure out if I need one, why did it work before, etc.

In any case, I think there are multiple wires that are crossed and we'll get them sorted out.

**Comment by vedantmgoyal9** [comment]
I've got a whole new issue, which I think **_is_** related to this version issue. You should also try using deploying functions from https://github.com/vedantmgoyal2009/winget-manifests-manager which error out with -
image
* https://github.com/vercel/vercel/issues/9393

**Comment by vedantmgoyal9** [comment]
@cb1kenobi any updates?

**Comment by cb1kenobi** [comment]
@vedantmgoyal2009 Sorry, been out sick and making slow progress. I'm still actively looking into this.

**Comment by cb1kenobi** [comment]
@vedantmgoyal2009 I did a ton of test with the go builder and I identified 6 significant issues that I've fixed in this PR: https://github.com/vercel/vercel/pull/9576. Once that PR has landed, we can update and merge this PR. I am also curious if https://github.com/vercel/vercel/issues/9393 will be fixed by the PR.

**Comment by vedantmgoyal9** [comment]
Thanks a lot🙏for looking into this issue. Hoping to have it merged soon so that I can move on with my project further.

**Review by cb1kenobi — APPROVED** [review]

**Comment by asparamancer** [comment]
Just an FYI, whenever I try using go 1.20 as the version in the mod file it can't build the functions. All errors are `xxx package not in GOROOT` etc, this is on a repo that has worked consistently - only change was updating to 28.17 and go 1.20

If I try and copy and paste the build command it has -w flag, which says is there but not defined. 

I'm on an M1 mac, vercel installed as global with npm (same error with yarn). 

I'll try and provide a minimal working example if I have time, but reverting to go 1.19 keeping 28.17 then builds fine.

**Comment by cb1kenobi** [comment]
@asparamancer are you using `vc build`?

**Pull request merged**
