### PR TITLE
[cli] update env var validation rule to allow name start with underscore

### PR DESCRIPTION
**Pull request by smaeda-ks**
internal ref: https://github.com/vercel/api/pull/20129

Vercel now accepts env var names that start with underscore.

### CODE REVIEW

**Review by trek — DISMISSED** [review]
Looks good! I can generate a changeset for you, if you like, to get this to pass linting. I'm assuming you'd say this is a new minor?

**Review by cb1kenobi — DISMISSED** [review]

**Comment by smaeda-ks** [comment]
@trek Thanks! 🙇  I don't know how we define patch vs minor in this repository, but I'll defer that to you...!

**Review by trek — DISMISSED** [review]

**Review by cb1kenobi — CHANGES_REQUESTED** [review]
Allowing `_` will now fail this integration test: https://github.com/vercel/vercel/blob/main/packages/cli/test/dev/integration-2.test.ts#L35

Fixture: https://github.com/vercel/vercel/blob/main/packages/cli/test/dev/fixtures/invalid-env-var-name/vercel.json#L8

The test should also be updated.

**Review by cb1kenobi — APPROVED** [review]
LGTM

**Review by trek — APPROVED** [review]

**Pull request merged**
