### PR TITLE
Return last deployment URL

### PR DESCRIPTION
**Pull request by elbuo8**
I've found myself writing some [scripts](https://github.com/elbuo8/yamilasusta.com/blob/master/deployment/deploy-master.sh#L3) to be able to obtain the last URL of the deployment since not all CI's have the clipboard available. 

If there is a way that I'm missing please let me know 😅 .

Also, more than glad to adjust too.

### CODE REVIEW

**Comment by matheuss** [comment]
We have some checks to determine if the process is running in a TTY, and if it's not, we only print the URL:

```
▲ gifs at master ✖ now | cat
https://gifs-hjxeapcijw.now.sh
▲ gifs at master ✖ 
```

So you can do things like this:

```
▲ gifs at master ✖ URL=$(now)
▲ gifs at master ✖ echo $URL
https://gifs-hjxeapcijw.now.sh
```

Not ideal, because then you lose the log of the deployment process.

I'm not sure if we'd like to have a `--last` flag like that – thoughts @rauchg @leo?

**Comment by elbuo8** [comment]
😓 didn't know that one.

**Comment by leo** [comment]
Thank you for the effort you've put into this, @elbuo8! But I think we shouldn't introduce another flag and make our system more complex just to make easier what's already pretty easy (like @matheuss stated it). 🙏

**Comment by elbuo8** [comment]
Totally 👍

**Pull request closed without merging**
