### PR TITLE
[tests] Skip tests that won't run on Windows due to 'mkdir -p' and symlinks

### PR DESCRIPTION
**Pull request by cb1kenobi**
Found a few tests that won't run on Windows. The project settings override test runs `mkdir -p` which errors. The other two build tests fail because they try to create symlinks.

#### Tests

- [x] The code changed/added as part of this PR has been covered with tests
- [x] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

### CODE REVIEW

**Comment by EndangeredMassa** [comment]
These tests run in [CI on Windows](https://github.com/vercel/vercel/runs/8235943942?check_suite_focus=true). What's the problem, specifically?

**Comment by cb1kenobi** [comment]
For the project settings override test (in cli), the unit test fails locally on a Windows machine because `yarn run build` exits with code `1` instead of `0`. It's trying to run `mkdir -p output && echo 3 > output/index.txt`. It seems to be fine when you run the tests from a clean fresh git clone (e.g. CI). However, subsequent unit test runs error out, possibly due to the test fixture directory not being clean.

```
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file output already exists.
Error occurred while processing: output.
```

If I check the filesystem, then there's a directory called `-p`. Windows aliases `mkdir` to `md`, but apparently it doesn't support the `-p` flag and proceeds to create a directory called `-p`. In any case, I still think the test is not Windows friendly.

The `importBuilders()` tests fail because of symlinks:

```
EPERM: operation not permitted, symlink '..\@vercel\build-utils' -> 'C:\Users\chris\AppData\Local\Temp\720c7e57\.vercel\builders\node_modules\@now\build-utils'
```

**Review by styfle — APPROVED** [review]

**Comment by EndangeredMassa** [comment]
Ah, so these happen to pass in CI, but they aren't really clean tests and they fail locally. Got it.

**Review by EndangeredMassa — APPROVED** [review]

**Comment by cb1kenobi** [comment]
@EndangeredMassa and the whole `mkdir -p` thing. :)

**Pull request merged**
