### PR TITLE
Automatically migrate the old configuration file

### PR DESCRIPTION
**Pull request by leo**
If the old config file exists, it will copy the data from there when initializing the new config.

### CODE REVIEW

**Review by matheuss — DISMISSED** [review]
LGTM overall, but we need a `info('Your credentials an config are now on ~/.now instead of ~/.now.json')` or something like that, similar to what we have at the end of `now login <provider>`

**Review by TooTallNate — APPROVED** [review]

**Comment by TooTallNate** [comment]
@matheuss You think so? `.now.json` is more of an implementation detail to me. I wouldn't expect users to be looking at it or modifying it manually in the normal use-case.

**Comment by matheuss** [comment]
@TooTallNate it's **very** sensitive stuff (e.g. an AWS API Key with Administrator access), so we need to let people now where their stuff is

**Comment by leo** [comment]
screen shot 2017-09-04 at 01 50 40

**Pull request merged**
