### PR TITLE
[build-utils][static-build][next] Force `YARN_NODE_LINKER="node-modules"` env var when executing `yarn`

### PR DESCRIPTION
**Pull request by TooTallNate**
### Related Issues

* https://vercel.com/knowledge/does-vercel-support-yarn-2
* https://github.com/vercel/vercel/discussions/4223
* https://github.com/vercel/vercel/discussions/4910
* https://github.com/vercel/vercel/issues/5136
* https://github.com/vercel/vercel/issues/5280

#### Tests

- [x] The code changed/added as part of this PR has been covered with tests
- [x] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

### CODE REVIEW

**Review by styfle — APPROVED** [review]

**Review by 88nssec — APPROVED** [review]
Approved

**Review by ijjk — APPROVED** [review]

**Comment by kachkaev** [comment]
@TooTallNate are there any plans to support yarn 2 without falling back to the `node_modules` folder? See https://github.com/yarnpkg/berry/issues/2031

Just tried `FORCE_BUILDER_TAG=canary` for [njt](https://github.com/kachkaev/njt/pull/29) and it worked, but `yarn install` was quite slow: more than one minute. It takes about 25 seconds to get this done on the main branch, which uses yarn 1. In theory yarn 2 installs should be faster because PnP does not involve the creation of thousands of files.

**Comment by leo** [comment]
@kachkaev This was just an MVP to make sure Yarn 2 works on Vercel!

The next iteration will let you make use of the true performance advantage.

**Comment by leo** [comment]
I recommend following the [Vercel Changelog](https://twitter.com/vercel_changes), where we'll let you know once support for Yarn 2 has landed entirely.

**Pull request merged**
