### PR TITLE
Add --remove-old flag to alias set command

### PR DESCRIPTION
**Pull request by rtsao**
Fixes https://github.com/zeit/now-cli/issues/691

### CODE REVIEW

**Comment by leo** [comment]
Thank you for the effort you've put into his! But please consider creating [an issue](https://github.com/zeit/now-cli/issues) the next time before you start tackling the topic, so that we can discuss it and agree on it. Because in this case, I don't think it's a good idea to merge this into the project, since we're trying to keep the core as small as possible.

The issue that you mentioned doesn't contain much feedback from any other person regarding whether or not this makes sense to implement. To be clear: There's no advantage in deleting old deployments and we don't require you to do so.

We'll be releasing support for plugins in the future, so this might be a great plugin... 😊

**Comment by rtsao** [comment]
Yeah, I would have made an issue for it but I found that existing one (with eight thumbs up reactions and no other comments/reactions).

Cool, I totally get the feature bloat factor, there's totally no reason it needs to be in core other than it was easier to implement there.

Looking forward to a plugin API!

**Comment by sholladay** [comment]
> There's no advantage in deleting old deployments

My team begs to disagree. Since CI deploys upwards of 10 times per day, our `now ls` output grows by at least 50 entries every single week. I suppose I could hire an intern to clean it up... 😄 

The compounding problem is that there is no system for tagging deployments. So we are unable to distinguish between legitimate experiments that people want to keep around vs the ghosts from previous CI deployments. We tried to use the frozen status of a deployment to tell them apart, but of course legitimate deploys can be in either state.

I would say I don't see an advantage to keeping around a deploy whose alias just got overwritten.

I am all in favor of the default behavior being to keep the old deploy around, just to be safe. But I definitely think this is a common use case and that it would benefit a lot of people. The issue reactions relative to other issues would seem to support this.

**Comment by rauchg** [comment]
Agreed that there are many things to improve here. At the very least, `now ls` can exclude old deployments. Also, one could set up 'garbage collection' policies so that the developers are not burdened by manual command execution.

Let's keep this discussion going.

**Comment by rauchg** [comment]
Thanks for weighing in @sholladay and everyone.

**Comment by rtsao** [comment]
In the meantime, I've implemented this in userland: https://github.com/rtsao/now-replace

**Comment by leo** [comment]
We can keep discussing this on https://github.com/zeit/now-cli/issues/969, if you want. This is a PR, so I'm closing it... 😊

**Pull request closed without merging**
