### PR TITLE
Adds `domains config <domain>` command to check if a domain is configured properly for now

### PR DESCRIPTION
**Pull request by mglagola**
Adds `domains config <domain>` command to ensure a domain is configured properly for now.

Successfully configured domain example:
```
now domains config test.external-test.xyz

> Success! "test.external-test.xyz" is properly configured for now
```

Incorrectly configured domain example:
```
now domains config bad.external-test.xyz

> Error! "bad.external-test.xyz" is not properly configured for now.
> CNAME record value for bad.external-test.xyz does not point to "alias.zeit.co.". Make sure the CNAME value for bad.external-test.xyz is properly configured to work with now.
```

### CODE REVIEW

**Comment by TooTallNate** [comment]
Is `domains config` really the best name for this command? Perhaps `domains verify` instead?

Also, I realize this message comes from the server-side, so not really related to this PR, but `Make sure the CNAME value for bad.external-test.xyz is properly configured to work with now.` is not very informative and doesn't give the user a path forward to fix the issue.

**Comment by mglagola** [comment]
@TooTallNate We already have a `domains verify` command, but i wonder if we can merge this `config` command with the existing `verify` command 🤔(will experiment with this)

The current `domains verify` command requires that the user has the domain added to their account and attempts to verify that the user owns the domain (via nameservers or TXT record). 

This `config` command just checks if a given domain (or subdomain) has all the appropriate DNS records in order to be used with **now**.

I agree that the message needs to be more descriptive 👍.

**Comment by javivelasco** [comment]
As this feature was added to show in the UI whether a domain is correctly configured or not maybe it's a good idea to check it when performing some other commands. For example, if you manually alias we can check the domain configuration when it's a custom domain. In case we detect it's misconfigured we can still create the alias but tell the user that it's not going to work giving a precise reason.

The same would work when issuing certs or even creating a deployment that automatically alias. We must be careful and do it in the client though so we don't add time response. What do you guys think?

**Review by javivelasco — COMMENTED** [review]
As this feature was added to show in the UI whether a domain is correctly configured or not maybe it's a good idea to check it when performing some other commands. For example, if you manually alias we can check the domain configuration when it's a custom domain. In case we detect it's misconfigured we can still create the alias but tell the user that it's not going to work giving a precise reason.

The same would work when issuing certs or even creating a deployment that automatically alias. We must be careful and do it in the client though so we don't add time response. What do you guys think?

**Pull request closed without merging**
