### PR TITLE
pass flags to subcommands

### LINKED ISSUE #3: Pass flags to subcommands
`now -d list`

should result in

`now list -d`

### PR DESCRIPTION
**Pull request by codyzu**
Instead of assuming the subcommand is the first argument, this enhancement searches for the first valid subcommand in all of the process arguments. The result being the arguments are more or less "re-ordered" to push all the flags after the subcommand. Processing of the the help command was then refactored to work with the new parsing.

@leo @rauchg this fixes #3. Let me know if there is something I can improve. cheers!

### CODE REVIEW

**Comment by rauchg** [comment]
This is really really great. Thanks @codyzu

**Comment by codyzu** [comment]
Glad to help!

I could probably add tests for this module by mocking cross-spawn (I'm a fan of [simple-mock](https://github.com/jupiter/simple-mock))... would this be interesting to you guys?

The other bin scripts seem harder to test because the flag validation is mixed in with the business logic, but maybe that could be improved later...

What do you think? @rauchg?

**Comment by rauchg** [comment]
@codyzu that actually would be _really_ awesome.

One clever way to avoid mocking could be to test for the `--help` flag?

`now --help alias` should equal `now alias --help`

A simple test for which help is reported (right now it incorrectly shows the `now` global help) would make this very solid IMHO

Let me know what you think

**Comment by codyzu** [comment]
@rauchg ok, this would involve some tests that spawn the now script and capture stdout to verify the correct help message is outputted... that seems possible. I can add that to verify everything works together (more like an integration test).

If you're not opposed, I'll give the mocking a stab (I've done this a lot during my day job) and see if the tests aren't too ugly. That way we can unit test _all_ the flag combinations...

Let me know if that's not direction you want to go.

btw, I tested this pull request manually, so if you're feeling pressed to get the issue resolved and released, you can merge it and I'll create a new one for the tests. Otherwise I'll keep working on this one.

**Comment by codyzu** [comment]
ah yeah, @rauchg, it gets messy with mocks... maybe you saw that coming... trying to spawn a child process with mocks :-( no no... I'll stick with your test idea :-)

**Comment by codyzu** [comment]
@rauchg I added the tests. I was forced to add compile as a `pretest` npm script because `bin/now.js` cannot be executed directly (issue with relative imports in `update.js`). So, the tests execute with the compiled script.

_This is ready to merge._

Let me know what you think.

**Comment by codyzu** [comment]
ping @rauchg @leo

**Comment by leo** [comment]
@codyzu Thanks a lot!

**Pull request merged**
