### PR TITLE
Including flag to list just deployments in READY state

### PR DESCRIPTION
**Pull request by romuloalves**
I miss a way to see just my deployments that is in `READY` state, so I developed a `--ready` flag to `now list`.

I know this is not a requested feature but can be very useful.

### CODE REVIEW

**Comment by jamo** [comment]
Just a random thought, one alternative would be to do filtering based on state, like `now ls --state READY`

**Comment by romuloalves** [comment]
It's a good way, I'm just in doubt about what is the easier.
I know this approach is useful for all states but I think some states can be "boring" to write all the command.

**Comment by leo** [comment]
I suggest doing it like @jamo [mentioned](https://github.com/zeit/now-cli/pull/514#issuecomment-299680114) it. Thanks for your effort, but we're not going to introduce a new flag just to reduce a command by a few characters!

I hope you understand that we need to keep the CLI as simple as possible in terms of options and commands available. 🙏

**Comment by romuloalves** [comment]
No problems! Thank you! 😊

**Pull request closed without merging**
