### PR TITLE
[now-routing-utils] Use 308 status code

### PR DESCRIPTION
**Pull request by styfle**
We decided that all of the new properties should default to 308 status code for any redirects.

### CODE REVIEW

**Review by leo — APPROVED** [review]

**Review by dav-is — CHANGES_REQUESTED** [review]
This either needs to be 307 or 308. 301 is deprecated

**Comment by styfle** [comment]
[308](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308) is not support in IE 11 on Windows 8.

I think we need to wait a year or two before using it as a default.

As far as I know, every browser supports [301](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301). Where do you see that its deprecated?

**Comment by dav-is** [comment]
@styfle We send a `Refresh` header along with 308s to support IE now

**Review by dav-is — CHANGES_REQUESTED** [review]
Let's switch cleanUrls to use 308 too

**Comment by styfle** [comment]
As we discussed in slack, old browsers and http clients that don't support 308 status codes probably don't support the latest ssl ciphers. So that means they already can't make a request, let alone see the the 308 response.

There's also a [`Refresh`](https://en.wikipedia.org/wiki/Meta_refresh) header that is sent along with 308 just in case the client doesn't know what to do with 308.

I updated this PR to use 308 👍

**Review by dav-is — APPROVED** [review]

**Pull request merged**
