### PR TITLE
fix: broken link in missing `start` script error

### PR DESCRIPTION
**Pull request by gtsiolis**

### CODE REVIEW

**Comment by Qix-** [comment]
Hi there - could you explain how this fixes a broken link?

**Comment by gtsiolis** [comment]
Hi Josh, I forgot to mention that I am using Hyper for macOS which takes into account the trailing dot after the URL, creating the following broken hyper link (`https://docs.npmjs.com/cli/start.`) which I actually clicked on as an early user of Now CLI. But this is not a problem for other terminal emulators, so feel free to dismiss this short-term fix since this is probably an issue with [Hyper](https://github.com/zeit/hyper).

**Comment by Qix-** [comment]
Oh I see. I'll make sure the Hyper team sees this - but could you instead change it to just remove the dot at the end instead of introducing a newline? :)

Thanks for the PR by the way!

**Comment by gtsiolis** [comment]
DONE. Thanks! :D

**Comment by Qix-** [comment]
Thank you :)

**Pull request merged**
