### PR TITLE
[cli] Fix color and indention in learn more link

### PR DESCRIPTION
**Pull request by dav-is**
CH-568

Before:
image

After:
Screenshot-2020-09-04-11:44

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Let's update the CLI test "next unsupported functions config shows warning link" so that it checks for new new format

**Comment by dav-is** [comment]
> Let's update the CLI test "next unsupported functions config shows warning link" so that it checks for new new format

This test doesn't use TTY, so this fix doesn't make any difference in its output

**Review by styfle — APPROVED** [review]
Thanks!

**Review by TooTallNate — APPROVED** [review]
The indentation part I think is inconsistent with the other times we render "Learn More" links, but code LGTM.

**Pull request merged**
