### PR TITLE
Do not delete the wildcard cert when deleting a cert by a CN

### PR DESCRIPTION
**Pull request by antonmoiseev**
This PR addresses two issues:

1. Currently if you attempt to delete a cert by a CN the command fails with the error:
    ```
    > Error! An unexpected error occurred in cert: TypeError: Cannot read property 'join' of undefined
    ```
    This happens because `getCertById()` request (that precedes certs lookup by CN) returns all of the account's certs even if the specified ID doesn't exist, so the execution on the client proceeds to the wrong branch.

    Probably you'd like to address this on the server as well, but the proposed CLI changes just [tighten requirements](https://github.com/zeit/now-cli/pull/1678/files#diff-d668eea43a9d7d49451ec6673d9b36bfR84) to the `getCertById()` response, so no temporary workarounds that would require a cleanup in the future.

2. And it addresses the originally reported issue (#1497) - makes sure that only the cert associated with the specified CN is deleted, keeping the wildcard cert safe.

### CODE REVIEW

**Comment by juliangruber** [comment]
Hey @anatrajkovska, could you please take a look at the merge conflicts?

**Comment by anatrajkovska** [comment]
@juliangruber Hey! I resolved the merge conflicts, but for some reason the integration tests are failing, specifically this test https://github.com/zeit/now-cli/blob/canary/test/integration.js#L217. 

It says that `stdout` is empty.

**Comment by juliangruber** [comment]
Sorry @anatrajkovska  I meant to mention @antonmoiseev 😨

**Comment by antonmoiseev** [comment]
@anatrajkovska thank you!

**Comment by xiaohuoni** [comment]
😭

**Comment by anatrajkovska** [comment]
Fixed the merge conflicts. 

@antonmoiseev Can you please check if the merging complies with your changes.

**Comment by antonmoiseev** [comment]
@anatrajkovska yes, it does. Isn't it the CI build checks out the PR's branch?

**Comment by anatrajkovska** [comment]
@antonmoiseev Yes it does, but since the file is refactored in TypeScript, there are some changes in the function you made the improvements. So I have slightly refactored your logic because of that. 

Just check the code again if it looks good to you.

**Comment by mglagola** [comment]
> 1. Currently if you attempt to delete a cert by a CN the command fails with the error...

This seems to be working in latest cli version

> 2. And it addresses the originally reported issue (#1497) - makes sure that only the cert associated with the specified CN is deleted, keeping the wildcard cert safe.

Going to fix this in API

**Pull request closed without merging**
