### PR TITLE
Add `teams ls` command

### PR DESCRIPTION
**Pull request by chabou**
As mentioned in #483, `now teams ls` is documented in help message but not implemented
Deeply inspired by `switch` command.

Design is minimalist:
capture d ecran 2017-05-21 a 02 19 03

### CODE REVIEW

**Comment by rauchg** [comment]
Beautiful :) Maybe add `case 'list'` as well?

**Comment by rauchg** [comment]
Also, can you try using a table (similar to `now domains ls` for example), so that it looks more consistent with how we render other lists?

We could do:

```
id             email / name          current?
chabou         chabou@delean.fr      ✓
winamax        Winamax
test-team1     Team1
```

What do you think?

**Comment by chabou** [comment]
Good idea for `list` alias.

I'll try to render this list as a table. So much clearer (and consistent)!

**Comment by chabou** [comment]
I added a basic, but generic, [table output primitive](https://github.com/chabou/now-cli/blob/66d62ed4e5f35ad7234ae1aa515584e0ccc7d069/lib/utils/output/table.js) and used it.

Result:
capture d ecran 2017-05-21 a 11 16 56

**Comment by albinekb** [comment]
I would remove the `current?` title, and make it just blank, and chance the check to the old `(current)` in bold 👌  but that's me 😄

**Comment by chabou** [comment]
New proposition with @albinekb inputs:
capture d ecran 2017-05-21 a 23 45 35

**Comment by albinekb** [comment]
😎

**Pull request merged**
