### PR TITLE
fix: Doc links in auth files

### PR DESCRIPTION
**Pull request by Zertsov**
Fixed the links in the auth files to reflect what the doc links currently are.

### CODE REVIEW

**Comment by EndangeredMassa** [comment]
The URLs appear to be correct as-is. Can you be specific about what you are seeing?

https://vercel.com/docs/projects/project-configuration#global-configuration/config-json
https://vercel.com/docs/projects/project-configuration#global-configuration/auth-json

**Comment by Zertsov** [comment]
> The URLs appear to be correct as-is. Can you be specific about what you are seeing?
> 
> https://vercel.com/docs/projects/project-configuration#global-configuration/config-json https://vercel.com/docs/projects/project-configuration#global-configuration/auth-json

Looks like when I click either of those it takes me to the same page instead of directly to where I'd assume they go to. Like in the `auth-json` route, I'd expect to be navigated to [here](https://vercel.com/docs/projects/project-configuration/global-configuration#auth.json), but currently the links just take me to the `Configuring Projects with Vercel` page

**Review by Ethan-Arrowood — CHANGES_REQUESTED** [review]
these links do not exist

**Comment by Zertsov** [comment]
@Ethan-Arrowood I'm a little unclear, if I go to the global configuration under project configuration docs, click on the `auth.json`, it puts https://vercel.com/docs/projects/project-configuration/global-configuration#auth.json into the address bar, which is what my changes point to as well

**Comment by Ethan-Arrowood** [comment]
I've copied and pasted the links here:

https://vercel.com/docs/project-configuration/global-configuration#config.json

https://vercel.com/docs/project-configuration/global-configuration#auth.json

When I navigate to either of those I get a 404.

**Comment by Zertsov** [comment]
oh I see now, it's because I'm blind and forgot `/projects/project-configuration...`

**Review by Ethan-Arrowood — APPROVED** [review]

**Review by EndangeredMassa — APPROVED** [review]

**Pull request merged**
