### PR TITLE
[node] fix WebAssembly bindings evaluating to `undefined`

### PR DESCRIPTION
**Pull request by Schniz**
This was broken since https://github.com/vercel/vercel/pull/8242, which accidentally pushed all WebAssembly modules to be nested under `global.wasmBindings` instead of being directly under the global scope.

### Related Issues

- This was broken since https://github.com/vercel/vercel/pull/8242

#### Tests

- [ ] The code changed/added as part of this PR has been covered with tests
- [ ] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

### CODE REVIEW

**Comment by Schniz** [comment]
cc @EndangeredMassa @TooTallNate how would you suggest me to test this to make sure it does not break in the future? I am not sure we have the foundations to test `vc dev` right now, but I might be wrong!

**Review by cb1kenobi — APPROVED** [review]
Tested and works!

**Review by EndangeredMassa — APPROVED** [review]
There is a test that basic WASM support works. That test passed in the offending PR: https://github.com/vercel/vercel/runs/7585545987?check_suite_focus=true

Is there deeper functionality we should add to that test? I'm confused about why that test wasn't failing.

**Comment by cb1kenobi** [comment]
Are you thinking of adding a `dev` test or fixing the test which incorrectly passed?

**Comment by EndangeredMassa** [comment]
Either one. As long as this is covered appropriately.

**Comment by Schniz** [comment]
@EndangeredMassa  can you point me to where I can find these tests so I would add another example?

**Comment by EndangeredMassa** [comment]
@Schniz certainly! https://github.com/vercel/vercel/blob/main/packages/node/test/fixtures/61-edge-function/vercel.json

**Review by EndangeredMassa — APPROVED** [review]
I verified that the new tests only works with the changes.

**Review by cb1kenobi — APPROVED** [review]

**Pull request merged**
