### PR TITLE
[WIP] Adjust Node.js CLI Plugin to use correct output

### PR DESCRIPTION
**Pull request by leo**
This pull request aligns the output of `vercel-plugin-node` with our other CLI Plugins.

The only change missing is one that @AndyBitz suggested, which changes the code path that writes the launcher file to write a JS file that imports the actual launcher file from the `.output/inputs` directory (only for the `.js` ext).

#### Tests

- [x] The code changed/added as part of this PR has been covered with tests
- [x] All tests pass locally with `yarn test-unit`

#### Code Review

- [x] This PR has a concise title and thorough description useful to a reviewer
- [x] Issue from task tracker has a link to this PR

### CODE REVIEW

**Comment by TooTallNate** [comment]
So what happens to the differences that plugin-node has already introduced? For example parsing the static config with the static-config module?

**Comment by leo** [comment]
I suggest adding that to the utility and only running it for the `.js` extension at the moment.

**Comment by TooTallNate** [comment]
It's still not very clear to me what this PR is accomplishing. What does "aligns the output of `vercel-plugin-node` with our other CLI Plugins" mean?

**Comment by TooTallNate** [comment]
> I suggest adding that to the utility and only running it for the `.js` extension at the moment.

In that case it should probably go into `@vercel/node` itself? Seems hacky to special-case a file extension in the general purpose utility module.

**Pull request closed without merging**
