### PR TITLE
[gatsby-plugin-now] Remove temporarily

### PR DESCRIPTION
**Pull request by AndyBitz**
Remove `gatsby-plugin-now` temporarily.

### CODE REVIEW

**Review by leo — APPROVED** [review]

**Review by styfle — COMMENTED** [review]
Why is this being removed?

**Comment by AndyBitz** [comment]
@styfle only temporary, since it is not needed at the moment and won't be for a while

**Comment by styfle** [comment]
@AndyBitz My understanding is that this plugin is currently injected into all gatsby deployments so removing it would be a breaking change (which is why you had to remove the `@now/static-build` tests).

Adding @lucleray to review this PR too.

*Update*: I was mistaken. The PR #3308 was never merged so this is a standalone plugin, not autoinjected.

**Comment by leo** [comment]
As we've ascertained on the call, it's not being invoked.

**Pull request merged**
