### PR TITLE
Improved deploying message

### LINKED ISSUE #806: `> Ready! https://xxx.now.sh (copied to clipboard)` should not say `Ready!`
```
> Deploying xxx under yyy
> Using Node.js 8.4.0 (default)
> Ready! https://xxx.now.sh (copied to clipboard) [24s]
> Initializing…
> Building
> ▲ npm install
> ✓ Using "yarn.lock"
> ⧗ Installing 67 main dependencies…
> ✓ Installed 911 modules [29s]
> ▲ npm run build
> > xxx@1.0.0 build /home/nowuser/src
> > next build
> > Using external babel configuration
> > Location: "/home/nowuser/src/.babelrc"
> > Using "webpack" config function defined in next.config.js.
```

I think `Ready!` is confusing here, especially with the use of an exclamation mark.

- It is not clear what is actually "ready".
- Every new user with think that there deploy is already finished, then find a 503 or something when its not.

I suggest being more clear about what is "ready", and removing the color and the exclamation point.

### PR DESCRIPTION
**Pull request by melvin0008**
Fixes #806

### CODE REVIEW

**Review by OlliV — APPROVED** [review]

**Comment by rauchg** [comment]
How about `> Started!` Keep in mind that by the time we print the URL we have everything necessary to build your deployment (all the sources) starting with API v2 ;)

**Comment by melvin0008** [comment]
`>Started!` seems good too. But `>Started! #{url}` seems to lack continuity in my opinion.

**Comment by rauchg** [comment]
"Started" can also be confusing with the _deployment instance_ actually starting. To be 100% clear, with API /v2 here's how it works:

- We `POST to /v2/deployments`. The deployment is **created** when that endpoint responds 200. The *prerequisite* of that endpoint is that all the sources for the deployment are there.
- The deployment is initially in the `INITIALIZING` state. At this point, we ensure there's a build running for that deployment
  - If the build fails, we go into `ERROR`
- If the build succeeds, we go into `READY`
  - At this point, the deployment is *complete*. It can be scaled infinitely, in every point of the world. `READY` and `ERROR` are final states.
  - As you can see, deployment is _separate_ from execution. For convenience, we will start an **instance** of your deployment in your nearest location, and at that point we will exit the process. This means that the URL you go to will be 100% ready if you choose to follow it, running your code.

You can see how this is now implemented for future deployments here:
https://github.com/zeit/now-cli/pull/993/files#diff-f082ee326f7b80cf9d3d439b44cc9926R799

**Comment by leo** [comment]
Not an easy decision for me, honestly.

I like the `Ready!` a lot because it signalises that the deployment is ready to accept requests and ready to be shared with other people (it just doesn't render your application yet).

But I also understand why some people might find it confusing...

**Comment by melvin0008** [comment]
@rauchg Thanks for explaining the deployment process in detail. How about Deployment uploaded to #{url} or just Uploaded to #{url} ?

**Comment by gtsiolis** [comment]
Given that `READY` is actually further down the lifecycle as described here (https://zeit.co/docs/deployment-types/lifecycle) I would go for `Started!` or `Deployment URL:`. 

Alternatively I would consider renaming the lifecycle state `DEPLOYING`  to `INITIALIZED` or something similar but I assume that would require further changes. Then `Started!` would become `Initialized!`.

Another thing to worry about is that the deployment actually becomes `READY` regardless of user input when the terminal prompts for approval while on OSS plan. So the code and logs are made public even without user consent which is also a privacy issue besides an obscure behavior.

```shell
> You (username) are on the OSS plan. Your code and logs will be made public.
> Are you sure you want to proceed with the deployment? [y|N] 
```

**Comment by leo** [comment]
Closing this now, since we're working on a proper solution in a different branch... 😊 

Thank you for your effort in this, people!

**Pull request closed without merging**
