### PR TITLE
[build-utils][node][python][ruby] Update error message for EOL runtimes

### PR DESCRIPTION
**Pull request by styfle**
This PR updates the error message when the runtime version detected is EOL

### CODE REVIEW

**Review by AndyBitz — APPROVED** [review]

**Comment by swarnava** [comment]
Do you want to include ?:

> This change is because Node.js 12 has reached end-of-life and has stopped receiving security updates.

**Review by ethomson — APPROVED** [review]

**Review by swarnava — APPROVED** [review]

**Comment by styfle** [comment]
@swarnava I think the message is already too long so I would prefer to keep it shorter to avoid burying the lede. Probably better to add more details to the linked docs.

**Comment by swarnava** [comment]
@styfle 

> @swarnava I think the message is already too long so I would prefer to keep it shorter to avoid burying the lede. Probably better to add more details to the linked docs.

good point. But doesn't look like we are showing https://vercel.link/node-version in current build error.

**Comment by styfle** [comment]
@swarnava It should be there at the top of the page where we show an error message and a button to click for more info

**Pull request merged**
