### PR TITLE
Added debounced waiting message to `now ls`

### PR DESCRIPTION
**Pull request by riddla**
Refs #1167, #1166

### CODE REVIEW

**Comment by rauchg** [comment]
I was thinking it might be a good idea to implement this directly in `wait`, so that it applies to all use cases? What do you think @leo ?

**Comment by leo** [comment]
@rauchg Generally, I would say it would be a good idea. However, I've seen you call such a behavior "unpure" and that the function should only do one thing: Output formatted text.

If I misunderstood that, let's do it! 🚀

**Comment by leo** [comment]
@riddla Can you also sync this fork with our `canary` branch, so that you have the latest tests running on your branch?

**Comment by riddla** [comment]
@leo, I synced the fork.
Do you want me to implement the debouncing directly in the `wait` function? If so, activated via a parameter or as default behaviour? 

How shall I proceed? :)

**Comment by riddla** [comment]
@leo I went ahead and did the implementation (as I needed to use the golden time my son was sleeping in my baby belly carry ;)) with a kind of higher order function right within the wait module.

As the `wait` function is now async we would need to spot the other usages and `await` there also.
But let`s discuss my approach first.

**Comment by riddla** [comment]
Hmmm. As I was thinking about async/await - my implementation might make no sense. As the spinner now is always shown, only debounced for 300 ms. 
Or am I mistaken?

**Comment by riddla** [comment]
I‘ll get rid of the „clever“ higher order function and solve it in the ‘wait‘ function directly.

**Review by leo — APPROVED** [review]

**Comment by leo** [comment]
Great addition, thank you! 😊 

This will be released on the `canary` channel, so everyone can try it out.

**Comment by leo** [comment]
@riddla I just found a bug. It keeps the "Fetching deployments" around after they've finished loading and rendering:

screen shot 2018-03-14 at 15 00 52

Do you have any idea what is causing this?

🙈

**Comment by riddla** [comment]
Ohhh. This happenend to me once before, but only on a zshell on my non-work MacBook with a screwed up config. I‘ll look into it. 
Thanks for your efforts so far :)

**Comment by riddla** [comment]
@leo As we were `awaiting` the list command and though its output, the spinner was not stopped until the output of `list` was already on TTY. As `ora` e.g. the spinners just clears the last line when it is stopped and as it assumes it was the last one to write to TTY we ended up with the behaviour/bug you discovered.

I opened up a new pull request with the former branch, see https://github.com/zeit/now-cli/pull/1192. 
Or should I have used a new branch for this?

**Pull request merged**
