### PR TITLE
[remix] Fix usage with `bun install`

### LINKED ISSUE #10488: Bun with Remix fails to build on a fresh project
Steps to repro:
- `bunx create-remix` 
- run `bun install` locally to create a `bun.lockb` file
- deploy project on vercel with default `remix` settings

Errors on build
```
Running "bun run build"
--
19:56:45.059 | $ remix build
19:56:45.880 | info  building... (NODE_ENV=production)
19:56:46.753 | info  built (873ms)
19:56:46.817 | Error: File /vercel/path0/api/build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js does not exist.
```

### PR DESCRIPTION
**Pull request by TooTallNate**
Fixes https://github.com/vercel/vercel/issues/10488.

### CODE REVIEW

**Review by cb1kenobi — APPROVED** [review]

**Review by trek — APPROVED** [review]

**Review by styfle — APPROVED** [review]

**Comment by marcelovicentegc** [comment]
Hi, folks! Just for the record, I was following https://github.com/vercel/vercel/issues/10494 and my fresh Remix + bun deployment (https://mapa-community-git-main-oficinadomarcelo.vercel.app/) keeps failing with:

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/build/build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js' imported from /var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:332:11)
    at moduleResolve (node:internal/modules/esm/resolve:995:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:939:12)
    at defaultResolve (node:internal/modules/esm/resolve:1181:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
INIT_REPORT Init Duration: 251.34 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

**Comment by TooTallNate** [comment]
@marcelovicentegc I tried those same reproduction steps again last night and it worked for me. Can you share your repository that reproduces the issue?

**Comment by marcelovicentegc** [comment]
Yes, absolutely @TooTallNate! Here it is: https://github.com/arqmapas/mapa.community. Thanks for the follow up

**Comment by TooTallNate** [comment]
@marcelovicentegc Add a `remix.config.js` file and it should work.

**Comment by marcelovicentegc** [comment]
@TooTallNate adding a remix.config.js file made it work. Thanks sir :hugs: !

**Comment by ghost** [comment]
Hellooo! Same error here  😢
```
2023-12-13T21:38:59.418Z	undefined	ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/build/build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js' imported from /var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:332:11)
    at moduleResolve (node:internal/modules/esm/resolve:995:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:939:12)
    at defaultResolve (node:internal/modules/esm/resolve:1181:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
INIT_REPORT Init Duration: 219.40 ms	Phase: init	Status: error	Error Type: Runtime.ExitError
2023-12-13T21:38:59.679Z	undefined	ERROR	Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/var/task/build/build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.js' imported from /var/task/build/server-build-nodejs-eyJydW50aW1lIjoibm9kZWpzIn0.mjs
    at new NodeError (node:internal/errors:405:5)
    at finalizeResolution (node:internal/modules/esm/resolve:332:11)
    at moduleResolve (node:internal/modules/esm/resolve:995:10)
    at moduleResolveWithNodePath (node:internal/modules/esm/resolve:939:12)
    at defaultResolve (node:internal/modules/esm/resolve:1181:79)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:835:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:77:40)
    at link (node:internal/modules/esm/module_job:76:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}
INIT_REPORT Init Duration: 253.26 ms	Phase: invoke	Status: error	Error Type: Runtime.ExitError
Error: Runtime exited with error: exit status 1
```

This is my repo if it's possible to help me as well. Thanks in advance :smile: 
https://github.com/Andyloz/my-notes

**Comment by marcelovicentegc** [comment]
Hey @Andyloz, I guess you might need to uncomment these lines from `remix.config.js`:

```js
  // appDirectory: "app",
  // assetsBuildDirectory: "public/build",
  // publicPath: "/build/",
  // serverBuildPath: "build/index.js",
```

**Pull request merged**
