### PR TITLE
refactor: example umi using v3, support prerender

### PR DESCRIPTION
**Pull request by ycjcl868**
examples refactoring using v3（support SSR and pre-render）

image

### CODE REVIEW

**Comment by ycjcl868** [comment]
ping

**Comment by mcsdevv** [comment]
Hello @ycjcl868, thank you for this contribution.

We are recommending static first as the best way to build applications on Vercel. Does Umi v3 work like that or is SSR a hard requirement?

**Comment by ycjcl868** [comment]
`exportStatic: {}` enabled prerender, so this is a static site in production, SSR site in development.

**Review by AndyBitz — DISMISSED** [review]
Looks good to me!

@mcsdevv @timothyis you'll have to check as well since you are code owners of `/examples`, and once merged we'll probably need to deploy it to our examples team as well.

**Pull request closed without merging**
