### PR TITLE
[cli] Pin `@vercel/static-build` to "0.17.6-canary.0"

### PR DESCRIPTION
**Pull request by TooTallNate**
It got de-synced in c68e83f9726e622c3366653aee2674e35ccf4bc9.

### CODE REVIEW

**Comment by styfle** [comment]
@TooTallNate But how? I thought lerna was supposed to bump all the packages that depend on it?

@AndyBitz Did you do a normal `yarn publish-canary` for c68e83f?

**Review by AndyBitz — APPROVED** [review]

**Review by styfle — APPROVED** [review]

**Comment by AndyBitz** [comment]
@styfle no, I've created it manually, because I didn't want to publish the CLI.

**Comment by TooTallNate** [comment]
@styfle <strike>I'm not sure how this keeps happening</strike> I see, @AndyBitz did a manual publish.

@AndyBitz When we do a manual publish like that, we need to remember to update the dep in `now-cli` as well to keep the yarn workspace linking intact.

**Comment by styfle** [comment]
@AndyBitz I see. I updated the wiki for this use case: https://github.com/vercel/vercel/wiki/Creating-a-Release#manual-publishing

**Pull request merged**
