### PR TITLE
[tests] Added lock file for normalize paths test fixture

### PR DESCRIPTION
**Pull request by cb1kenobi**
Added a lock file to the normalize paths text fixture to speed up install dependencies.

#### Tests

- [x] The code changed/added as part of this PR has been covered with tests
- [x] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

### CODE REVIEW

**Review by styfle — APPROVED** [review]

**Comment by styfle** [comment]
@cb1kenobi How about adding assertions for `routes` here?

https://github.com/vercel/vercel/blob/48eb72055603c954b7e399e7783474fd0e87316b/packages/next/test/unit/fixtures/01-normalize-paths/index.test.js#L27

**Comment by cb1kenobi** [comment]
> @cb1kenobi How about adding assertions for `routes` here?
> 
> https://github.com/vercel/vercel/blob/48eb72055603c954b7e399e7783474fd0e87316b/packages/next/test/unit/fixtures/01-normalize-paths/index.test.js#L27

I looked into it, but `routes` doesn't contain any "paths" per se. It's basically a bunch of catch-all patterns, so I didn't think there was anything related to the path normalization to test in `routes`.

**Review by TooTallNate — APPROVED** [review]

**Comment by styfle** [comment]
@cb1kenobi Right, they are not file paths they are routes so they should always contain `/` and never `\` unless escaping regex in `src`. But `dest` should never have `\`.

I was pretty sure these were incorrectly using `path.join()` before and it was changed to use `path.posix.join()`

**Comment by cb1kenobi** [comment]
@styfle You are correct. Added some assertions here: https://github.com/vercel/vercel/pull/8609.

**Pull request merged**
