### PR TITLE
[frameworks] Fix Dojo logo

### PR DESCRIPTION
**Pull request by AndyBitz**
Use the existing PNG for Dojo, instead of the SVG, which does not work.

### CODE REVIEW

**Review by leo — CHANGES_REQUESTED** [review]
Why?

**Comment by AndyBitz** [comment]
Because the SVG doesn't work

**Review by leo — CHANGES_REQUESTED** [review]
Why do SVGs not work? Many frameworks have SVG logos in our list.

Also, let's explain this in the PR description next time (instead of me asking 😄).

**Review by leo — CHANGES_REQUESTED** [review]
Furthermore, if `.svg` "doesn't work" (which I still don't know the reason for), it should be removed from the repo.

**Comment by AndyBitz** [comment]
@leo this specific SVG does not work.
And the PNG was there before I added the broken SVG.
The path in `frameworks.json` was wrong, I just reverted what I added and made it work like it was intended.

**Review by leo — APPROVED** [review]

**Review by styfle — APPROVED** [review]

**Pull request merged**
