### PR TITLE
[next] fix test missing `yarn.lock` file

### PR DESCRIPTION
**Pull request by styfle**
- Follow up to https://github.com/vercel/vercel/pull/10630

Was passing in the PR https://github.com/vercel/vercel/actions/runs/6386018083/job/17332012211#step:9:269

But is failing on main https://github.com/vercel/vercel/actions/runs/6386371621/job/17332970210

Looks like the `yarn.lock` was removed right before merging so this PR adds it back.

INC-442

### CODE REVIEW

**Review by ijjk — COMMENTED** [review]
Let's remove the need for these yarn.lock files instead

x-ref: https://github.com/vercel/vercel/commit/993cd0ae9f1d5d19fbd4a84c062642acee83664a

**Comment by csabapalfi** [comment]
Sorry @styfle! I have accidentally removed this yarn.lock while you were reviewing. Apologies about this. I was trying to cleanup the PR and I thought I accidentally commited this lockfile.

**Comment by styfle** [comment]
Closing per @ijjk

**Comment by styfle** [comment]
I'm opening this one again since https://github.com/vercel/vercel/pull/10631 was reverted

**Review by ijjk — APPROVED** [review]

**Review by cb1kenobi — APPROVED** [review]

**Comment by styfle** [comment]
Fast tracking since since `test unit (@vercel/next` is passing now

**Pull request merged**
