### PR TITLE
[cli] Update `@vercel/fun` to v1.1.1

### PR DESCRIPTION
**Pull request by G-Rath**
This is a repeat of #10946 - v1.1.1 was released specifically to address the security vulnerabilities in downstream dependencies due to using exact constraints (https://github.com/vercel/fun/pull/98 and https://github.com/vercel/fun/pull/95).

~I have _not_ created a changeset as I assume this change is too small to be worth bumping any packages for, but can include one if desired.~

### CODE REVIEW

**Review by TooTallNate — DISMISSED** [review]

**Comment by EndangeredMassa** [comment]
Test failure:

```
● [vercel dev] Use `@vercel/python` with Flask requirements.txt
  Failed to fetch "http://localhost:3009/api/user?name=Alice", received 502, expected 200, id: dev1::dev1::mumeo-1712944062140-18999544fcdb:
  An error occurred with this application.
  NO_RESPONSE_FROM_FUNCTION
    42 |       if (res.status !== opts.status) {
    43 |         const text = await res.text();
  > 44 |         throw new Error(
       |               ^
    45 |           `Failed to fetch "${url}", received ${res.status}, expected ${
    46 |             opts.status
    47 |           }, id: ${res.headers.get('x-vercel-id')}:\n\n${text}\n\n`
    at retry.retries (test/dev/utils.js:44:15)
        at runMicrotasks (<anonymous>)
    at testPath (test/dev/utils.js:175:15)
    at helperTestPath (test/dev/utils.js:513:9)
    at test/dev/integration-2.test.ts:119:5
    at Object.<anonymous> (test/dev/utils.js:515:7)
```

**Comment by EndangeredMassa** [comment]
The error from `vc dev` is: "ModuleNotFoundError: No module named 'dataclasses'"


```
> Building @vercel/python@latest:api/user.py
Installing required dependencies...
> Built @vercel/python@latest:api/user.py [6s]
Traceback (most recent call last):
  File "/Users/smassa/Library/Caches/com.vercel.fun/runtimes/python3/../python/bootstrap.py", line 147, in <module>
    lambda_runtime_main()
  File "/Users/smassa/Library/Caches/com.vercel.fun/runtimes/python3/../python/bootstrap.py", line 127, in lambda_runtime_main
    fn = lambda_runtime_get_handler()
  File "/Users/smassa/Library/Caches/com.vercel.fun/runtimes/python3/../python/bootstrap.py", line 113, in lambda_runtime_get_handler
    mod = importlib.import_module(module_name)
  File "/Users/smassa/Library/Caches/com.vercel.fun/runtimes/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/folders/gy/4wttbrqd7r58_c4pwb6hv4p80000gn/T/zeit-fun-7637276ea946a/vc__handler__python.py", line 13, in <module>
    __vc_spec.loader.exec_module(__vc_module)
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./api/user.py", line 1, in <module>
    from flask import Flask, Response, request
  File "/var/folders/gy/4wttbrqd7r58_c4pwb6hv4p80000gn/T/zeit-fun-7637276ea946a/flask/__init__.py", line 3, in <module>
    from werkzeug.exceptions import abort as abort
  File "/var/folders/gy/4wttbrqd7r58_c4pwb6hv4p80000gn/T/zeit-fun-7637276ea946a/werkzeug/__init__.py", line 2, in <module>
    from .test import Client as Client
  File "/var/folders/gy/4wttbrqd7r58_c4pwb6hv4p80000gn/T/zeit-fun-7637276ea946a/werkzeug/test.py", line 30, in <module>
    from .sansio.multipart import Data
  File "/var/folders/gy/4wttbrqd7r58_c4pwb6hv4p80000gn/T/zeit-fun-7637276ea946a/werkzeug/sansio/multipart.py", line 2, in <module>
    from dataclasses import dataclass
ModuleNotFoundError: No module named 'dataclasses'
LambdaError: RequestId: 5f5b4917-f06f-4584-8651-86f5400a97b1 Process exited before completing request
    at Lambda.<anonymous> (/Users/smassa/source/vercel/vercel-2/node_modules/.pnpm/@vercel+fun@1.1.1/node_modules/@vercel/fun/src/index.ts:103:10)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/smassa/source/vercel/vercel-2/node_modules/.pnpm/@vercel+fun@1.1.1/node_modules/@vercel/fun/dist/src/index.js:24:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by G-Rath** [comment]
@EndangeredMassa is it possible that those errors are unrelated or due to the PR being opened by me? (i.e. my CI runs might not have permission to access particular resources).

It seems surprising to me that minor updates to packages that are considered extremely stable would cause errors in Python based tests, and when the `vercel/fun` CI passed for this change

**Comment by G-Rath** [comment]
@TooTallNate @EndangeredMassa any update on when this might be landed? I've now opened #11543 to track all the security vulnerabilities currently reported by using Vercel, which this will address a few of.

**Comment by jeffsee55** [comment]
`"ModuleNotFoundError: No module named 'dataclasses'"` is due to this using Python 3.6, `dataclasses` wasn't added until [Python 3.7](https://docs.python.org/3/library/dataclasses.html). 

Shown on this line:
```
  File "/Users/smassa/Library/Caches/com.vercel.fun/runtimes/python3/lib/python3.6/importlib/__init__.py", line 126, in import_module
```
I'm pretty fuzzy on what's going on here, and which aspects of the setup are responsible for the Python version, this test can be seen running successfully recently [here](https://github.com/vercel/vercel/actions/runs/9573710567/job/26395682631#step:8:1532), though I get this same error when I run the test locally, regardless of what version of `@vercel/fun` I'm using.

**Comment by jeffsee55** [comment]
@trek I recall us having some issues recently with python fixtures/examples not being pinned? This fixture looks ok to me but I don't know enough about Python infra to really say 

https://github.com/vercel/vercel/blob/5c21d400bd729822d6f65f8515b9424d88a5308f/packages/cli/test/dev/fixtures/python-flask/requirements.txt

**Comment by trek** [comment]
@jeffsee55 we did https://github.com/vercel/examples/pull/927/files. Possibly `Flask==2.0.1` should be bumped to latest of `2.x` to match? The slightly older version might not work with the newer python version? Or alternatively we should bump to to latest major (3.x)?

**Pull request closed without merging**
