### PR TITLE
Use single domain call to remove add domains domains

### PR DESCRIPTION
**Pull request by joecohens**

### CODE REVIEW

**Comment by leo** [comment]
Gonna defer this to @javivelasco – the expert on this topic

**Review by javivelasco — COMMENTED** [review]
I'm not sure if we should consume v4 yet but I think it has now the final format. So yeah, let's merge and ship

**Comment by javivelasco** [comment]
Test are failing though @joecohens

**Comment by leo** [comment]
Re-started the tests!

**Pull request merged**
