### PR TITLE
[node] add test for multiple cookies on edge

### PR DESCRIPTION
**Pull request by dstaley**
This PR adds a test case demonstrating the ability to set multiple cookies in an edge runtime API handler.

### CODE REVIEW

**Comment by dstaley** [comment]
I believe this will be fixed in the next release of `edge-runtime`, which should contain [this PR](https://github.com/vercel/edge-runtime/pull/645) which fixed `set-cookie` header parsing.

**Comment by Ethan-Arrowood** [comment]
Have you seen #10767 yet? This might have some impact to your work.

**Comment by Kikobeats** [comment]
the test is passing green to me <picture data-single-emoji=":thinkies:" title=":thinkies:">:thinkies:</picture> 

CleanShot 2023-11-03 at 10 04 12@2x

**Comment by dstaley** [comment]
@Kikobeats you skipped the test this PR adds :) It's named `allow setting multiple cookies with same name on edge runtime`

**Comment by dstaley** [comment]
With the changes from https://github.com/vercel/vercel/pull/10712, this test case is now passing.

```
@vercel/node:test-unit:   ✓ allow setting multiple cookies with same name (2834 ms)
@vercel/node:test-unit:   ✓ allow setting multiple cookies with same name on edge runtime (2832 ms)
```

**Review by Ethan-Arrowood — APPROVED** [review]
I like it 👍

**Comment by EndangeredMassa** [comment]
We test this in a different way here: https://github.com/vercel/vercel/blob/main/packages/node/test/dev-fixtures/multiple-cookies.ts

Maybe we should do both? Closing for now.

**Pull request closed without merging**
