### PR TITLE
[next][redwood][static-build] Remove frontend runtimes

### PR DESCRIPTION
**Pull request by TooTallNate**
This change was made so runtimes aren't separated into another codebase. We want folks to use `next dev` and `next build`, not a custom-built `deployPlatform dev`. Further, we're now documenting how to [add frameworks](https://vercel.com/docs/more/adding-your-framework) to the Vercel platform using the standard filesystem interface, without having to learn custom APIs.

### CODE REVIEW

**Review by styfle — DISMISSED** [review]
Nice! We want folks to just use `next dev` and `next build`, not `deployPlatform dev`

https://twitter.com/rauchg/status/1370430137699770370

**Review by styfle — APPROVED** [review]

**Review by Timer — APPROVED** [review]

**Review by pacocoursey — APPROVED** [review]

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
There are no related links or explanations, Is it no longer public or is it using another tool?

**Comment by b6pzeusbc54tvhw5jgpyw8pwz2x6gs** [comment]
@TooTallNate @Timer @styfle @pacocoursey 
There are no related links or explanations, Is it no longer public or is it using another tool?

**Comment by andrestone** [comment]
Great monetization efforts! Keep up!

**Pull request merged**
