### PR TITLE
[cli] Add node_modules/.bin to PATH instead of running npx/yarn run

### PR DESCRIPTION
**Pull request by cb1kenobi**
`runDevCommand()` assumes the dev command is an npm package and thus uses `npx` or `yarn run` to execute it. In the case of a Hugo-based app, there is no npm package, so we want spawn to find Hugo in the `PATH`. Then for Node-based apps, instead of `npx`, spawn should find the command since `node_modules/.bin` has been added to the `PATH`.

### Related Issues

> https://github.com/vercel/customer-issues/issues/871

#### Tests

- [ ] The code changed/added as part of this PR has been covered with tests
- [x] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

### CODE REVIEW

**Comment by TooTallNate** [comment]
Current tests seem ok with it. We should add a new test as well.

**Comment by cb1kenobi** [comment]
@TooTallNate what do you think the new test would test that the existing tests aren't covering?

**Comment by EndangeredMassa** [comment]
Can we add a hugo test to show this working?

**Comment by cb1kenobi** [comment]
Closing in favor of https://github.com/vercel/vercel/pull/8890 due to several Hugo related files being updated thanks to prettier.

**Pull request closed without merging**
