### PR TITLE
Added missing deps to package.json

### PR DESCRIPTION
**Pull request by spal1**
When I tried to npm install, it was complaining about some dependencies not existing. I added these dependencies to package.json

image

@leo quick fix?

### CODE REVIEW

**Comment by leo** [comment]
Thanks for the effort you've put into this 😊 But `npm install` doesn't generate such error messages. Maybe you got it from running `npm run dev` inside the repositorie's directory?

I tried running it on all branches and it always works fine - just like the installating of Now CLI itself (`npm install now -g`).

**Comment by spal1** [comment]
@leo Sorry, I actually ran `npm run build` and received the errors in the photo above.

**Comment by matheuss** [comment]
@spal1 thank you 😱 I wonder how they went missing from `package.json` 😥

**Comment by leo** [comment]
Seems like they were previously defined by sub dependencies, so it just worked without any errors for me. But you're right, they should be defined in `package.json`... 👍

**Pull request merged**
