### PR TITLE
[node-bridge] Catch invalid HTTP request headers

### PR DESCRIPTION
**Pull request by TooTallNate**
In some rare cases, the proxy layer passes what Node.js considers an
invalid HTTP request header causing the `http.request()` function to
throw an error, such as:

```
TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token ["cookie"]
```

So instead, use `req.setHeader()` API with try/catch to skip invalid
HTTP headers and print a message for the deployment logs with debugging
information. This way, the HTTP request will still go through, with
a missing header, rather than causing the whole function to 500.

### CODE REVIEW

**Review by lucleray — COMMENTED** [review]
Can we add a test for this behavior?

**Review by styfle — COMMENTED** [review]
Are we fixing this in the wrong place? Seems like it would affect other Runtimes too so maybe now-proxy should drop the header instead?

**Comment by TooTallNate** [comment]
@styfle I'm not really sure tbh. The cookie value was valid for the web browser, and also accepted by the proxy layer. So I'm curious if the fault lies in Node.js' HTTP parser being _too strict_, or if the proxy layer is mangling the data somehow.

This PR is an attempt to shed light on what the values are since it logs the name and value when `setHeader()` throws an error.

**Comment by lucleray** [comment]
@TooTallNate You can reproduce the error by adding the special character `“` in a header, for example:

```sh
node -e "require('http').createServer((req, res) => res.setHeader('h', '“')).listen(80)" &
curl http://localhost:80
```

**Comment by TooTallNate** [comment]
@lucleray @styfle Added a test.

**Review by styfle — APPROVED** [review]
Nice!

**Review by lucleray — APPROVED** [review]

**Pull request merged**
