### PR TITLE
[examples] Update Astro example to v2

### PR DESCRIPTION
**Pull request by swarnava**

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
This is swapping from pnpm to yarn, is that intentional?

I think we should stick with pnpm since thats what it was using before.

**Comment by swarnava** [comment]
For some reason, I pnpm-lock file isn't being generated when I run `pnpm install`. any idea why?

**Comment by styfle** [comment]
Could be corepack. You could try it in a separate directory first and copy the lockfile and package.json over. Also could try updating pnpm.

**Review by styfle — APPROVED** [review]
Thanks!

**Pull request merged**
