### PR TITLE
Increase static-build integration test pool

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**

### CODE REVIEW

**Review by trek — DISMISSED** [review]

**Comment by EndangeredMassa** [comment]
What's the current average time these take before changes? What impact do we expect this to have on this package's and overall test run times?

**Review by styfle — COMMENTED** [review]
I think you need to update the chunk-tests script (wasn’t it at 7 instead of 8)

**Comment by Ethan-Arrowood** [comment]
From latest Test run on `main` (https://github.com/vercel/vercel/actions/runs/6304368691/job/17115635623)

The 5 static-build e2e-tests took: 44, 51, 42, 37, and 38 seconds to run

**Comment by Ethan-Arrowood** [comment]
Test timings from this PR:

https://github.com/vercel/vercel/actions/runs/6318024618/job/17156149557

1: 4m 7s
2: 8m 41s
3: 10m 9s
4: 5m 32s
5: 4m 29s 
6: 10m 18s
7: 4m 34s
8: 13m 21s

**Comment by Ethan-Arrowood** [comment]
From a recent no-change run:

https://github.com/vercel/vercel/actions/runs/6318113736/job/17156464823
1: 7m 19s
2: 13m 31s
3: 6m 55s
4: 11m 59s
5: 13m 10s


this pr is useless. parallelizing isn't going to fix it. We need to fix the tests taking 10+ minutes.

**Comment by styfle** [comment]
@Ethan-Arrowood I think the issue is that the grouping is alphabetic instead of by time.

So it looks like all the gatsby tests are grouped together which are the slowest.

If those could be distributed evenly among jobs, it would speed things up.

https://github.com/vercel/vercel/actions/runs/6318024618/job/17156151260#step:9:66

**Comment by Ethan-Arrowood** [comment]
They aren't the only ones being so slow. There's something earlier on also taking 10+ mins

**Pull request closed without merging**
