### PR TITLE
Debug logs - Convert object to string 

### PR DESCRIPTION
**Pull request by sreeramjayan**
Since opts.body is an object it wasn't rendered with string literals. Hence converted the object to a string before displaying it.

Fixes https://github.com/zeit/now-cli/issues/1277

### CODE REVIEW

**Comment by rauchg** [comment]
The gotcha is that we don't want to pay the performance cost of JSON serialization if it's not enabled.

**Comment by sreeramjayan** [comment]
In that case, would it be better to just display the endpoint along with the duration and not the body?
> POST https://api.zeit.co/v4/now/deployments: 558.025ms

**Comment by rauchg** [comment]
@sreeramjayan I think so, or conditionally detect debugging being enabled and serialize it

**Comment by sreeramjayan** [comment]
> conditionally detect debugging being enabled and serialize it

This message shows up only if debugging is enabled. Therefore shouldn't it be fine the way it is?

**Comment by pranaygp** [comment]
@sreeramjayan also note that `opts.body` isn't necessarily an object. It can also be a Buffer or Stream, and so this gets tricky

Also, the body could be really long in which case the debug output could actually fill your terminal screen and make it harder to debug something. 

Maybe it's better to leave it as is (JS will show you `[object Object]` or `<Buffer de ad be ef ...>` or some other truncated output (only the case of `Stream` isn't truncated) and then, if you're actively debugging and want to know the `body`, add your own temp `console.log` statement ¯\\_(ツ)_/¯

**Comment by sreeramjayan** [comment]
@pranaygp 
You have a valid point. I shall close this PR.

**Pull request closed without merging**
