### PR TITLE
Support attempting to remove without confirm prompt

### PR DESCRIPTION
**Pull request by remy**
Adds `-f` to `now rm` command, i.e. `now rm -f <id>`

Makes for a slightly faster (and less interrupted) workflow for mass deleting deployments.

Also includes help output.

### CODE REVIEW

**Comment by jamo** [comment]
This feature would indeed be helpful.
However, I think that instead of `-f --force` we should call the option `-y --yes` since it's essentially just automatically answering yes to the confirmation prompts.

**Comment by remy** [comment]
Sure, I can change. I was just following conventions in the cli args
already (and the pattern from the Unix command `rm`).

**Comment by rase-** [comment]
I don't have a very strong opinion on whether it should be `-y` or `-f`. I'd be fine just leaving it `-f`, even though it's not _exactly_ the same thing as it is for similarly named unix tool. Anyways, I think it would be nice to add the same flag to all `rm` subcommands, such as `now domains rm`, so we don't introduce divergence in how they work.

**Comment by remy** [comment]
I can add those to the PR.

**Comment by leo** [comment]
No changes for about a month, so I introduced it using this commit: https://github.com/zeit/now-cli/commit/26afd83c1af236b9b067549a56c85e8185235b0b (support for other sub commands coming). 🙏

**Comment by remy** [comment]
WFM.

I actually ended up discovering that I could send multiple deployment ids to `now rm` so it made things a little easier for me (saying yes once > saying yes every time). 

Though, I have found a new bug in that (0.3x seems to hang when fed via STDIN compared to 0.2x - but I'll raise a separate issue).

Ta!

**Pull request closed without merging**
