### PR TITLE
[cli] Render an error page when middleware explodes.

### PR DESCRIPTION
**Pull request by gdborton**
### Related Issues

This adds error handling for middleware in `vc dev`

Local looks a little different than production:
Local
image

Production
image

#### Tests

- [ ] The code changed/added as part of this PR has been covered with tests
- [x] All tests pass locally with `yarn test-unit`

#### Code Review

- [x] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

### CODE REVIEW

**Review by styfle — COMMENTED** [review]
Please add a test so we don't regress

**Comment by gdborton** [comment]
@styfle I added an integration test.  I'm not sure how it's generated, but I noticed that the response in the test has the error code that I'm passing to sendError. This isn't the same response as what I'd see in the browser, but I didn't look too deeply into it as it seems be validating what I was trying to test.

**Review by styfle — APPROVED** [review]
Thanks!

**Comment by styfle** [comment]
@gdborton Its probably a different response because the `Accept` header isn't provided by the test but it is by your browser.

**Review by TooTallNate — APPROVED** [review]

**Pull request merged**
