### PR TITLE
added "--target none" support to now-cli 

### PR DESCRIPTION
**Pull request by wiiiimm**
pending for api-zeit updates

### CODE REVIEW

**Comment by michaellopez** [comment]
We would like this, so that we can reuse same command and just swap the value to pass to `--target` depending on pipeline on GitLab. Right now we have to have different commands for some pipelines as they should not alias more than the initial alias we get from Now, only way to accomplish that is to NOT pass the `--target` flag. With this PR it would allow us the same command for all pipelines and pass different values to `--target`

**Comment by TooTallNate** [comment]
Hey @williamli, can you re-create a new PR for this but based on the `canary` branch? We don't do PRs directly to `master` branch.

**Comment by StefMa** [comment]
Why was this closed?
Is there a new pr?

**Comment by michaellopez** [comment]
@StefMa I guess @williamli never sent a new PR against canary so it was closed as to not have lingering PRs open that don't move forward.
I can rebase this on canary though, I just didn't want to step on any toes, specially not OP.

**Comment by TooTallNate** [comment]
@StefMa @michaellopez This would require some server-side changes that have not been implemented as well, so let's keep it closed for now.

**Pull request closed without merging**
