### PR TITLE
[build-utils] Replace cross-spawn with execa

### PR DESCRIPTION
**Pull request by frencojobs**
### Related Issues

There is an error that happens when using the [vercel-dev-runtime](https://github.com/TooTallNate/vercel-dev-runtime) as a runtime on the deployed functions. 

errer

It seems that the error comes from the `runPackageJsonScript` function. It only happens on the deployed functions and can't be reproduced locally with the `vercel dev` command.

It seems to be caused by the [cross-spawn](https://github.com/moxystudio/node-cross-spawn/issues/104) package which is used to execute the scripts from `package.json`. Even though I couldn't find an exact relation between the mentioned issue and the error, the error can be easily fixed by switching to the [execa](https://github.com/sindresorhus/execa) package.

This PR replaces all usages of `cross-spawn` with `execa`.

#### Tests

- [ ] The code changed/added as part of this PR has been covered with tests
- [x] All tests pass locally with `yarn test-unit`

#### Code Review

- [ ] This PR has a concise title and thorough description useful to a reviewer
- [ ] Issue from task tracker has a link to this PR

### CODE REVIEW

**Comment by TooTallNate** [comment]
Interesting. I'm curious how you are testing. Do you have an idea about why the `runNpmInstall()` works, but then immediately afterwards the `runPackageJsonScript()` is failing? That's the part that I haven't figure out.

**Comment by frencojobs** [comment]
Ok, so I did a little more debugging and I think I found the culprit.

This line of code overrides the environment variables of the spawning process, which would basically remove the `PATH` variable, therefore, removing the installed path of `yarn`.
```ts
const env: typeof process.env = { ...spawnOpts?.env };
// ...
await spawnAsync('yarn', ['run', scriptName], {
    ...spawnOpts,
    env, // <- this
    cwd: destPath,
    prettyCommand,
  });
```

To test the scenario, I passed the `PATH` variable from the vercel-dev-runtime like this,
```ts
await runPackageJsonScript(workPath, 'build', {
  env: {
    PATH: process.env.PATH,
  },
});
```
and it worked. Here is the code https://github.com/frencojobs/vercel-dev-runtime/blob/fab5484fd2c1d00c8f48577ac56b85b3ec65d30c/index.js#L21. It's not using the execa version though. [Here](https://vercel.com/frenco/vercel-dart/dih2gvpdy) is a succeeded log from a deployment using it.

The reason why it worked with execa is that execa uses this function to add all required variables before passing them to the process spawner.

```ts
const getEnv = ({env: envOption, extendEnv, preferLocal, localDir, execPath}) => {
  // `extendEnv` option is `true` by default in execa
  const env = extendEnv ? {...process.env, ...envOption} : envOption;
	if (preferLocal) {
	  return npmRunPath.env({env, cwd: localDir, execPath});
	}
  return env;
};
```

So, we can also just merge that env object with `process.env` before passing it to the `cross-spawn`, instead of using execa I guess. But if there's no specific reason to use cross-spawn instead of execa, execa seems like a better option IMO.

What do you think?

**Comment by styfle** [comment]
I think the issue was introduced in #5552

We should probably change this line:

```ts
const env: typeof process.env = { ...spawnOpts?.env };
```

to this:

```ts
const env: typeof process.env = { ...process.env, ...spawnOpts?.env };
```

**Comment by TooTallNate** [comment]
Hey @frencojobs, thanks for the PR btw. I think #5841 is a better solution in this case. Let me know what you think.

**Comment by frencojobs** [comment]
Cool, thanks. I just love that it works now.

**Pull request closed without merging**
