### PR TITLE
Fixed the input and output utilities

### PR DESCRIPTION
**Pull request by leo**
After this PR, the input fields will work properly again and no errors will be swallowed.

### CODE REVIEW

**Comment by Qix-** [comment]
Any reason why `error()` doesn't just output the message? Wrapping all occurrences of `error()` with `console.error()` isn't very DRY.

**Comment by leo** [comment]
@Qix- @rauchg said it's very important that a function only does as less as possible (like composing a string) - he criticized that on Now Desktop as well, so I converted it into log statements that are logging a string that was composed by a function.

The statements you in the code here were written by him before, so I just extended that. 

BTW: I did it just like you described in all of my code before he told me to do it otherwise.

**Comment by Qix-** [comment]
I just worry that someone is going to mistake `error()` for actually outputting an error message, thus running the risk of an error message silently being ignored.

**Review by Qix- — APPROVED** [review]
LGTM, glad to see this fixed. :)

**Comment by matheuss** [comment]
@Qix- @leo we moved away from having `output` utilities to `console.log` because having side effects like that makes it very hard (if not impossible) to perform nested calls like this:
```
console.log(info(
  `AWS credentials found in ${param(AWS_CREDENTIALS_FILE_PATH)}.`,
  `  Would you like to use them?`
))
```

**Comment by Qix-** [comment]
@matheuss but in that case, `console.log` wouldn't be necessary? I'm not following that specific logic.

I agree with the sentiment, but I don't necessarily like the non-DRY-ness of it all - especially since, as I mentioned before, it'd be easy for someone to forget a logging statement and accidentally hide an error message because they didn't know to output to the console.

We see this kind of problem frequently over at Chalk (where people don't realize they need to `console.log()` the result of chalk calls).

I just worry.

**Pull request merged**
