### PR TITLE
feat(turbo): add support for turbo 2 configuration

### PR DESCRIPTION
**Pull request by chris-olszewski**
With the release of Turborepo 2 we're renaming `pipeline` to `tasks`. 

This PR updates the default settings logic to look in `tasks` for a `build` task definition in addition to looking at `pipeline`. It also updates the message to no longer mention Turbo configuration in `package.json` as this is fully ignored in Turborepo 2.

Added a quick unit test to verify `build` task definitions are found in the `tasks` section of `turbo.json`.

Please let me know if there are other tests/places I should update.

### CODE REVIEW

**Review by trek — APPROVED** [review]

**Review by jeffsee55 — APPROVED** [review]
👍 

**(non-blocking):** My only thought was whether or not it'd be appropriate to display a message that `pipeline` has been renamed or if there's a codemod available.

**Comment by chris-olszewski** [comment]
> My only thought was whether or not it'd be appropriate to display a message that pipeline has been renamed or if there's a codemod available.

We have that messaging available if someone attempts to use a turbo 1 config with turbo 2 so we'll display that info a little bit later in the build process.

**Comment by kduprey** [comment]
@chris-olszewski - I'm getting build errors currently when attempting to update to Turbo 2.0 myself, specifically with the turbo.json config. 

```bash
00:36:46.478 |  
00:36:46.478 | x failed to parse turbo json
00:36:46.478 |  
00:36:46.479 | Error: turbo_json_parse_error
00:36:46.479 |  
00:36:46.479 | x Found an unknown key `tasks`.
00:36:46.479 | ,-[3:1]
00:36:46.479 | 3 \|   "globalDependencies": [".env"],
00:36:46.479 | 4 \|   "tasks": {
00:36:46.479 | :   ^^^^^^^
00:36:46.480 | 5 \|     "build": {
00:36:46.480 | `----
00:36:46.480 |  
00:36:46.496 | Error: Command "cd ../.. && turbo run build --filter={apps/cms}..." exited with 1
00:36:47.040
```

Is there an issue that has been opened for this?

**Comment by kevsjh** [comment]
seeing the same issue as well on vercel build. 


Error: turbo_json_parse_error
```
--
01:58:18.881 |  
01:58:18.881 | x Found an unknown key `tasks`.
01:58:18.881 | ,-[4:1]

```
no issue on local build

**Comment by wernst** [comment]
Seeing the same issue that @kduprey and @kevsjh  have noted above

**Pull request merged**
